/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Local interface for AuthBoss.
 */
public interface AuthBossLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Add buffered listener to register login audits post commit. This allows for read-only operations to succeed properly when accessed via HQU
    */
   public void startup(  ) ;

   /**
    * Login a user.
    * @param username The name of the user.
    * @param password The password.
    * @return An integer representing the session ID of the logged-in user.
    */
   public int login( java.lang.String username,java.lang.String password ) throws java.lang.SecurityException, javax.security.auth.login.LoginException, org.hyperic.hq.common.ApplicationException, org.hyperic.util.ConfigPropertyException;

   /**
    * Login a guest.
    * @return An integer representing the session ID of the logged-in user.
    */
   public int loginGuest(  ) throws java.lang.SecurityException, javax.security.auth.login.LoginException, org.hyperic.hq.common.ApplicationException, org.hyperic.util.ConfigPropertyException;

   /**
    * Logout a user.
    * @param sessionID The session id for the current user
    */
   public void logout( int sessionID ) ;

   /**
    * Check if a user is logged in.
    * @param username The name of the user.
    * @return a boolean| true if logged in and false if not.
    */
   public boolean isLoggedIn( java.lang.String username ) ;

   /**
    * Add a user to the internal database
    * @param sessionID The session id for the current user
    * @param username The username to add
    * @param password The password for this user
    */
   public void addUser( int sessionID,java.lang.String username,java.lang.String password ) throws org.hyperic.hq.auth.shared.SessionException;

   /**
    * Change a password for a user
    * @param sessionID The session id for the current user
    * @param username The user whose password should be updated
    * @param password The new password for the user
    */
   public void changePassword( int sessionID,java.lang.String username,java.lang.String password ) throws javax.ejb.FinderException, org.hyperic.hq.authz.shared.PermissionException, org.hyperic.hq.auth.shared.SessionException;

   /**
    * Check existence of a user
    */
   public boolean isUser( int sessionID,java.lang.String username ) throws org.hyperic.hq.auth.shared.SessionTimeoutException, org.hyperic.hq.auth.shared.SessionNotFoundException;

}
