/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Local home interface for AuthBoss.
 */
public interface AuthBossLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AuthBossLocal";
   public static final String JNDI_NAME="LocalAuthBoss";

   public org.hyperic.hq.bizapp.shared.AuthBossLocal create()
      throws javax.ejb.CreateException;

}
