/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Home interface for ConfigBoss.
 */
public interface ConfigBossHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ConfigBoss";
   public static final String JNDI_NAME="ejb/bizapp/ConfigBoss";

   public org.hyperic.hq.bizapp.shared.ConfigBoss create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
