/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Local home interface for ConfigBoss.
 */
public interface ConfigBossLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ConfigBossLocal";
   public static final String JNDI_NAME="LocalConfigBoss";

   public org.hyperic.hq.bizapp.shared.ConfigBossLocal create()
      throws javax.ejb.CreateException;

}
