/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Remote interface for ConfigBoss.
 */
public interface ConfigBoss
   extends javax.ejb.EJBObject
{
   /**
    * Get the top-level configuration properties
    */
   public java.util.Properties getConfig(  )
      throws org.hyperic.util.ConfigPropertyException, java.rmi.RemoteException;

   /**
    * Get the configuration properties for a specified prefix
    */
   public java.util.Properties getConfig( java.lang.String prefix )
      throws org.hyperic.util.ConfigPropertyException, java.rmi.RemoteException;

   /**
    * Set the top-level configuration properties
    */
   public void setConfig( int sessId,java.util.Properties props )
      throws org.hyperic.hq.common.ApplicationException, org.hyperic.util.ConfigPropertyException, java.rmi.RemoteException;

   /**
    * Set the configuration properties for a prefix
    */
   public void setConfig( int sessId,java.lang.String prefix,java.util.Properties props )
      throws org.hyperic.hq.common.ApplicationException, org.hyperic.util.ConfigPropertyException, java.rmi.RemoteException;

   /**
    * Restart the config Service
    */
   public void restartConfig(  )
      throws java.rmi.RemoteException;

   /**
    * Perform routine database maintenance. Must have admin permissions.
    * @return The time it took to vaccum, in milliseconds, or -1 if the database is not PostgreSQL.
    */
   public long vacuum( int sessionId )
      throws org.hyperic.hq.auth.shared.SessionTimeoutException, org.hyperic.hq.auth.shared.SessionNotFoundException, org.hyperic.hq.authz.shared.PermissionException, java.rmi.RemoteException;

}
