/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Local home interface for ControlBoss.
 */
public interface ControlBossLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ControlBossLocal";
   public static final String JNDI_NAME="LocalControlBoss";

   public org.hyperic.hq.bizapp.shared.ControlBossLocal create()
      throws javax.ejb.CreateException;

}
