/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Local home interface for EmailManager.
 */
public interface EmailManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EmailManagerLocal";
   public static final String JNDI_NAME="LocalEmailManager";

   public org.hyperic.hq.bizapp.shared.EmailManagerLocal create()
      throws javax.ejb.CreateException;

}
