/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Home interface for GalertBoss.
 */
public interface GalertBossHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GalertBoss";
   public static final String JNDI_NAME="ejb/bizapp/GalertBoss";

   public org.hyperic.hq.bizapp.shared.GalertBoss create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
