/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Remote interface for LatherBoss.
 */
public interface LatherBoss
   extends javax.ejb.EJBObject
{

   public org.hyperic.lather.LatherValue dispatchWithTx( org.hyperic.lather.LatherContext ctx,java.lang.String method,org.hyperic.lather.LatherValue arg )
      throws org.hyperic.lather.LatherRemoteException, java.rmi.RemoteException;

   public org.hyperic.lather.LatherValue dispatchWithoutTx( org.hyperic.lather.LatherContext ctx,java.lang.String method,org.hyperic.lather.LatherValue arg )
      throws org.hyperic.lather.LatherRemoteException, java.rmi.RemoteException;

   /**
    * The main dispatch command which is called via the JBoss-lather servlet. It is the responsibility of this routine to take the method/args, and route it to the correct method.
    * @param ctx Information about the remote caller
    * @param method Name of the method to invoke
    * @param arg LatherValue argument object to pass to the method
    * @return an instantiated subclass of the LatherValue class, representing the result of the invoked method
    */
   public org.hyperic.lather.LatherValue dispatch( org.hyperic.lather.LatherContext ctx,java.lang.String method,org.hyperic.lather.LatherValue arg )
      throws org.hyperic.lather.LatherRemoteException, java.rmi.RemoteException;

}
