/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

import org.hyperic.lather.LatherContext;
import org.hyperic.lather.LatherRemoteException;
import org.hyperic.lather.LatherValue;

/**
 * Local interface for LatherBoss.
 */
public interface LatherBoss
{

   public LatherValue dispatchWithTx( LatherContext ctx,String method,LatherValue arg ) throws LatherRemoteException;

   public LatherValue dispatchWithoutTx( LatherContext ctx,String method,LatherValue arg ) throws LatherRemoteException;

   /**
    * The main dispatch command which is called via the JBoss-lather servlet. It is the responsibility of this routine to take the method/args, and route it to the correct method.
    * @param ctx Information about the remote caller
    * @param method Name of the method to invoke
    * @param arg LatherValue argument object to pass to the method
    * @return an instantiated subclass of the LatherValue class, representing the result of the invoked method
    */
   public LatherValue dispatch( LatherContext ctx,String method,LatherValue arg ) throws LatherRemoteException;

}
