/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Local home interface for MeasurementBoss.
 */
public interface MeasurementBossLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MeasurementBossLocal";
   public static final String JNDI_NAME="LocalMeasurementBoss";

   public org.hyperic.hq.bizapp.shared.MeasurementBossLocal create()
      throws javax.ejb.CreateException;

}
