/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

/**
 * Local home interface for ProductBoss.
 */
public interface ProductBossLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ProductBossLocal";
   public static final String JNDI_NAME="LocalProductBoss";

   public org.hyperic.hq.bizapp.shared.ProductBossLocal create()
      throws javax.ejb.CreateException;

}
