/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.measurement.shared;

import java.util.Collection;

import org.hyperic.hq.galerts.server.session.GalertAuxLog;
import org.hyperic.hq.galerts.server.session.GalertDef;
import org.hyperic.hq.measurement.galerts.MetricAuxLog;
import org.hyperic.hq.measurement.server.session.MetricAuxLogPojo;

/**
 * Local interface for MetricAuxLogManager.
 */
public interface MetricAuxLogManager {

    public MetricAuxLogPojo create(GalertAuxLog log, MetricAuxLog logInfo);

    public void removeAll(GalertDef def);

    public MetricAuxLogPojo find(GalertAuxLog log);

    /**
     * Callback, invoked when metrics are deleted. Since we still want to keep
     * the measurement around, we delete the value from the metric_aux_log and
     * transform the entry in the galert_aux_log to a regular entry.
     */
    public void metricsDeleted(Collection<Integer> mids);

}
