alter table HQADMIN.EAM_ACTION  shrink space compact;
alter table HQADMIN.EAM_ACTION  shrink space;
alter table HQADMIN.EAM_AGENT  shrink space  compact;
alter table HQADMIN.EAM_AGENT  shrink space;
alter table HQADMIN.EAM_AGENT_TYPE  shrink space  compact;
alter table HQADMIN.EAM_AGENT_TYPE  shrink space;
alter table HQADMIN.EAM_AIQ_IP  shrink space  compact;
alter table HQADMIN.EAM_AIQ_IP  shrink space;
alter table HQADMIN.EAM_AIQ_PLATFORM  shrink space  compact;
alter table HQADMIN.EAM_AIQ_PLATFORM  shrink space;
alter table HQADMIN.EAM_AIQ_SERVER  shrink space  compact;
alter table HQADMIN.EAM_AIQ_SERVER  shrink space;
alter table HQADMIN.EAM_AIQ_SERVICE  shrink space  compact;
alter table HQADMIN.EAM_AIQ_SERVICE  shrink space;
alter table HQADMIN.EAM_AI_AGENT_REPORT  shrink space  compact;
alter table HQADMIN.EAM_AI_AGENT_REPORT   shrink space;
alter table HQADMIN.EAM_ALERT  shrink space  compact;
alter table HQADMIN.EAM_ALERT  shrink space;
alter table HQADMIN.EAM_ALERT_ACTION_LOG  shrink space  compact; 
alter table HQADMIN.EAM_ALERT_ACTION_LOG  shrink space;
alter table HQADMIN.EAM_ALERT_CONDITION  shrink space  compact;
alter table HQADMIN.EAM_ALERT_CONDITION  shrink space;
alter table HQADMIN.EAM_ALERT_CONDITION_LOG  shrink space  compact;
alter table HQADMIN.EAM_ALERT_CONDITION_LOG  shrink space;
alter table HQADMIN.EAM_ALERT_DEFINITION  shrink space  compact;
alter table HQADMIN.EAM_ALERT_DEFINITION  shrink space;
alter table HQADMIN.EAM_ALERT_DEF_STATE  shrink space  compact;
alter table HQADMIN.EAM_ALERT_DEF_STATE  shrink space;
alter table HQADMIN.EAM_APPLICATION  shrink space  compact;
alter table HQADMIN.EAM_APPLICATION  shrink space;
alter table HQADMIN.EAM_APPLICATION_TYPE  shrink space  compact;
alter table HQADMIN.EAM_APPLICATION_TYPE  shrink space;
alter table HQADMIN.EAM_APP_SERVICE  shrink space  compact;
alter table HQADMIN.EAM_APP_SERVICE  shrink space;
alter table HQADMIN.EAM_APP_TYPE_SERVICE_TYPE_MAP  shrink space  compact;
alter table HQADMIN.EAM_APP_TYPE_SERVICE_TYPE_MAP  shrink space;
alter table HQADMIN.EAM_AUDIT  shrink space  compact;
alter table HQADMIN.EAM_AUDIT  shrink space;
alter table HQADMIN.EAM_AUTOINV_HISTORY  shrink space compact; 
alter table HQADMIN.EAM_AUTOINV_HISTORY  shrink space;
alter table HQADMIN.EAM_AUTOINV_SCHEDULE  shrink space  compact;
alter table HQADMIN.EAM_AUTOINV_SCHEDULE  shrink space;
alter table HQADMIN.EAM_CALENDAR  shrink space  compact;
alter table HQADMIN.EAM_CALENDAR  shrink space;
alter table HQADMIN.EAM_CALENDAR_ENT  shrink space  compact;
alter table HQADMIN.EAM_CALENDAR_ENT  shrink space;
alter table HQADMIN.EAM_CALENDAR_WEEK  shrink space  compact;
alter table HQADMIN.EAM_CALENDAR_WEEK  shrink space;
alter table HQADMIN.EAM_CONFIG_PROPS  shrink space  compact;
alter table HQADMIN.EAM_CONFIG_PROPS  shrink space;
alter table HQADMIN.EAM_CONFIG_RESPONSE  shrink space  compact;
alter table HQADMIN.EAM_CONFIG_RESPONSE  shrink space;
alter table HQADMIN.EAM_CONTROL_HISTORY  shrink space  compact;
alter table HQADMIN.EAM_CONTROL_HISTORY  shrink space;
alter table HQADMIN.EAM_CONTROL_SCHEDULE  shrink space  compact;
alter table HQADMIN.EAM_CONTROL_SCHEDULE  shrink space;
alter table HQADMIN.EAM_CPROP  shrink space  compact;
alter table HQADMIN.EAM_CPROP  shrink space;
alter table HQADMIN.EAM_CPROP_KEY  shrink space  compact;
alter table HQADMIN.EAM_CPROP_KEY  shrink space;
alter table HQADMIN.EAM_CRISPO  shrink space compact; 
alter table HQADMIN.EAM_CRISPO  shrink space;
alter table HQADMIN.EAM_CRISPO_ARRAY  shrink space compact; 
alter table HQADMIN.EAM_CRISPO_ARRAY  shrink space;
alter table HQADMIN.EAM_CRISPO_OPT  shrink space compact; 
alter table HQADMIN.EAM_CRISPO_OPT  shrink space;
alter table HQADMIN.EAM_CRITERIA  shrink space compact; 
alter table HQADMIN.EAM_CRITERIA  shrink space;
alter table HQADMIN.EAM_DASH_CONFIG  shrink space compact; 
alter table HQADMIN.EAM_DASH_CONFIG  shrink space;
alter table HQADMIN.EAM_ERROR_CODE  shrink space compact; 
alter table HQADMIN.EAM_ERROR_CODE  shrink space;
alter table HQADMIN.EAM_ESCALATION  shrink space compact; 
alter table HQADMIN.EAM_ESCALATION  shrink space;
alter table HQADMIN.EAM_ESCALATION_ACTION  shrink space compact; 
alter table HQADMIN.EAM_ESCALATION_ACTION  shrink space;
alter table HQADMIN.EAM_ESCALATION_STATE  shrink space compact; 
alter table HQADMIN.EAM_ESCALATION_STATE  shrink space;
alter table HQADMIN.EAM_EVENT_LOG  shrink space compact; 
alter table HQADMIN.EAM_EVENT_LOG  shrink space;
alter table HQADMIN.EAM_EXEC_STRATEGIES  shrink space compact; 
alter table HQADMIN.EAM_EXEC_STRATEGIES  shrink space;
alter table HQADMIN.EAM_EXEC_STRATEGY_TYPES  shrink space compact; 
alter table HQADMIN.EAM_EXEC_STRATEGY_TYPES  shrink space;
alter table HQADMIN.EAM_GALERT_ACTION_LOG  shrink space compact; 
alter table HQADMIN.EAM_GALERT_ACTION_LOG  shrink space;
alter table HQADMIN.EAM_GALERT_AUX_LOGS  shrink space compact; 
alter table HQADMIN.EAM_GALERT_AUX_LOGS  shrink space;
alter table HQADMIN.EAM_GALERT_DEFS  shrink space compact; 
alter table HQADMIN.EAM_GALERT_DEFS  shrink space;
alter table HQADMIN.EAM_GALERT_LOGS  shrink space compact; 
alter table HQADMIN.EAM_GALERT_LOGS  shrink space;
alter table HQADMIN.EAM_GTRIGGERS  shrink space compact; 
alter table HQADMIN.EAM_GTRIGGERS  shrink space;
alter table HQADMIN.EAM_GTRIGGER_TYPES  shrink space compact; 
alter table HQADMIN.EAM_GTRIGGER_TYPES  shrink space;
alter table HQADMIN.EAM_IP  shrink space compact; 
alter table HQADMIN.EAM_IP  shrink space;
alter table HQADMIN.EAM_MEASUREMENT  shrink space compact; 
alter table HQADMIN.EAM_MEASUREMENT  shrink space;
alter table HQADMIN.EAM_MEASUREMENT_BL  shrink space compact; 
alter table HQADMIN.EAM_MEASUREMENT_BL  shrink space;
alter table HQADMIN.EAM_MEASUREMENT_CAT  shrink space compact; 
alter table HQADMIN.EAM_MEASUREMENT_CAT  shrink space;
alter table HQADMIN.EAM_MEASUREMENT_TEMPL  shrink space compact; 
alter table HQADMIN.EAM_MEASUREMENT_TEMPL  shrink space;
alter table HQADMIN.EAM_METRIC_AUX_LOGS  shrink space compact; 
alter table HQADMIN.EAM_METRIC_AUX_LOGS  shrink space;
alter table HQADMIN.EAM_METRIC_PROB  shrink space compact; 
alter table HQADMIN.EAM_METRIC_PROB  shrink space;
alter table HQADMIN.EAM_MONITORABLE_TYPE  shrink space compact; 
alter table HQADMIN.EAM_MONITORABLE_TYPE  shrink space;
alter table HQADMIN.EAM_NUMBERS  shrink space compact; 
alter table HQADMIN.EAM_NUMBERS  shrink space;
alter table HQADMIN.EAM_OPERATION  shrink space compact; 
alter table HQADMIN.EAM_OPERATION  shrink space;
alter table HQADMIN.EAM_PLATFORM  shrink space compact; 
alter table HQADMIN.EAM_PLATFORM  shrink space;
alter table HQADMIN.EAM_PLATFORM_SERVER_TYPE_MAP  shrink space compact; 
alter table HQADMIN.EAM_PLATFORM_SERVER_TYPE_MAP  shrink space;
alter table HQADMIN.EAM_PLATFORM_TYPE  shrink space compact; 
alter table HQADMIN.EAM_PLATFORM_TYPE  shrink space;
alter table HQADMIN.EAM_PLUGIN  shrink space compact; 
alter table HQADMIN.EAM_PLUGIN  shrink space;
alter table HQADMIN.EAM_PRINCIPAL  shrink space compact; 
alter table HQADMIN.EAM_PRINCIPAL  shrink space;
alter table HQADMIN.EAM_REGISTERED_TRIGGER  shrink space compact; 
alter table HQADMIN.EAM_REGISTERED_TRIGGER  shrink space;
alter table HQADMIN.EAM_REQUEST_STAT  shrink space compact; 
alter table HQADMIN.EAM_REQUEST_STAT  shrink space;
alter table HQADMIN.EAM_RESOURCE  shrink space compact; 
alter table HQADMIN.EAM_RESOURCE  shrink space;
alter table HQADMIN.EAM_RESOURCE_AUX_LOGS  shrink space compact; 
alter table HQADMIN.EAM_RESOURCE_AUX_LOGS  shrink space;
alter table HQADMIN.EAM_RESOURCE_EDGE  shrink space compact; 
alter table HQADMIN.EAM_RESOURCE_EDGE  shrink space;
alter table HQADMIN.EAM_RESOURCE_GROUP  shrink space compact; 
alter table HQADMIN.EAM_RESOURCE_GROUP  shrink space;
alter table HQADMIN.EAM_RESOURCE_RELATION  shrink space compact; 
alter table HQADMIN.EAM_RESOURCE_RELATION  shrink space;
alter table HQADMIN.EAM_RESOURCE_TYPE  shrink space compact; 
alter table HQADMIN.EAM_RESOURCE_TYPE  shrink space;
alter table HQADMIN.EAM_RES_GRP_RES_MAP  shrink space compact; 
alter table HQADMIN.EAM_RES_GRP_RES_MAP  shrink space;
alter table HQADMIN.EAM_ROLE  shrink space compact; 
alter table HQADMIN.EAM_ROLE  shrink space;
alter table HQADMIN.EAM_ROLE_CALENDAR  shrink space compact; 
alter table HQADMIN.EAM_ROLE_CALENDAR  shrink space;
alter table HQADMIN.EAM_ROLE_OPERATION_MAP  shrink space compact; 
alter table HQADMIN.EAM_ROLE_OPERATION_MAP  shrink space;
alter table HQADMIN.EAM_ROLE_RESOURCE_GROUP_MAP   shrink space compact; 
alter table HQADMIN.EAM_ROLE_RESOURCE_GROUP_MAP  shrink space;
alter table HQADMIN.EAM_SERVER  shrink space compact; 
alter table HQADMIN.EAM_SERVER  shrink space;
alter table HQADMIN.EAM_SERVER_TYPE  shrink space compact; 
alter table HQADMIN.EAM_SERVER_TYPE  shrink space;
alter table HQADMIN.EAM_SERVICE  shrink space compact; 
alter table HQADMIN.EAM_SERVICE  shrink space;
alter table HQADMIN.EAM_SERVICE_DEP_MAP  shrink space compact; 
alter table HQADMIN.EAM_SERVICE_DEP_MAP  shrink space;
alter table HQADMIN.EAM_SERVICE_REQUEST  shrink space compact; 
alter table HQADMIN.EAM_SERVICE_REQUEST  shrink space;
alter table HQADMIN.EAM_SERVICE_TYPE  shrink space compact; 
alter table HQADMIN.EAM_SERVICE_TYPE  shrink space;
alter table HQADMIN.EAM_SRN  shrink space compact; 
alter table HQADMIN.EAM_SRN  shrink space;
alter table HQADMIN.EAM_STAT_ERRORS  shrink space compact; 
alter table HQADMIN.EAM_STAT_ERRORS  shrink space;
alter table HQADMIN.EAM_SUBJECT  shrink space compact; 
alter table HQADMIN.EAM_SUBJECT  shrink space;
alter table HQADMIN.EAM_SUBJECT_ROLE_MAP  shrink space compact; 
alter table HQADMIN.EAM_SUBJECT_ROLE_MAP  shrink space;
alter table HQADMIN.EAM_UI_ATTACHMENT  shrink space compact; 
alter table HQADMIN.EAM_UI_ATTACHMENT  shrink space;
alter table HQADMIN.EAM_UI_ATTACH_ADMIN  shrink space compact; 
alter table HQADMIN.EAM_UI_ATTACH_ADMIN  shrink space;
alter table HQADMIN.EAM_UI_ATTACH_MAST  shrink space compact; 
alter table HQADMIN.EAM_UI_ATTACH_MAST  shrink space;
alter table HQADMIN.EAM_UI_ATTACH_RSRC  shrink space compact; 
alter table HQADMIN.EAM_UI_ATTACH_RSRC  shrink space;
alter table HQADMIN.EAM_UI_PLUGIN  shrink space compact; 
alter table HQADMIN.EAM_UI_PLUGIN  shrink space;
alter table HQADMIN.EAM_UI_VIEW  shrink space compact; 
alter table HQADMIN.EAM_UI_VIEW  shrink space;
alter table HQADMIN.EAM_UI_VIEW_ADMIN  shrink space compact; 
alter table HQADMIN.EAM_UI_VIEW_ADMIN  shrink space;
alter table HQADMIN.EAM_UI_VIEW_MASTHEAD  shrink space compact; 
alter table HQADMIN.EAM_UI_VIEW_MASTHEAD  shrink space;
alter table HQADMIN.EAM_UI_VIEW_RESOURCE  shrink space compact; 
alter table HQADMIN.EAM_UI_VIEW_RESOURCE  shrink space;
alter table HQADMIN.EAM_UPDATE_STATUS  shrink space compact; 
alter table HQADMIN.EAM_UPDATE_STATUS  shrink space;
alter table HQADMIN.EAM_VIRTUAL  shrink space compact; 
alter table HQADMIN.EAM_VIRTUAL  shrink space;
