// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hyperic.hq.domain;

import java.lang.String;

privileged aspect Resource_Roo_JavaBean {
    
    public String Resource.getName() {
        return this.name;
    }
    
    public void Resource.setName(String name) {
        this.name = name;
    }
    
}
