/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.bizapp.shared;

import org.hyperic.hq.auth.shared.SessionException;
import org.hyperic.hq.bizapp.server.session.UpdateStatusMode;

/**
 * Local interface for UpdateBoss.
 */
public interface UpdateBoss {

    /**
     * Meant to be called internally by the fetching thread
     */
    public void fetchReport();

    /**
     * Returns null if there is no status report (or it's been ignored), else
     * the string status report
     */
    public java.lang.String getUpdateReport();

    public void setUpdateMode(int sess, UpdateStatusMode mode) throws SessionException;

    public UpdateStatusMode getUpdateMode();

    public void ignoreUpdate();

}
