/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.events.shared;

import java.util.Date;

/**
 * Local interface for HeartBeatService.
 */
public interface HeartBeatService {
    /**
     * Dispatch a heart beat.
     * @param beatTime The heart beat time.
     */
    public void dispatchHeartBeat(Date beatTime);

}
