/*                                                                 
 * NOTE: This copyright does *not* cover user programs that use HQ 
 * program services by normal system calls through the application 
 * program interfaces provided as part of the Hyperic Plug-in Development 
 * Kit or the Hyperic Client Development Kit - this is merely considered 
 * normal use of the program, and does *not* fall under the heading of 
 * "derived work". 
 *  
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc. 
 * This file is part of HQ.         
 *  
 * HQ is free software; you can redistribute it and/or modify 
 * it under the terms version 2 of the GNU General Public License as 
 * published by the Free Software Foundation. This program is distributed 
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. 
 *                
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 
 * USA. 
 */

package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * AlertCondition generated by hbm2java
 */
public class AlertCondition  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private long _version_;
     private Integer type;
     private boolean required;
     private Integer measurementId;
     private String name;
     private String comparator;
     private double threshold;
     private String optionStatus;
     private AlertDefinition alertDefinitionId;
     private Integer tiggerId;
     private Collection alertConditions;

     // Constructors

    /** default constructor */
    public AlertCondition() {
    }

	/** minimal constructor */
    public AlertCondition(Integer type, boolean required) {
        this.type = type;
        this.required = required;
    }
    /** full constructor */
    public AlertCondition(Integer type, boolean required, Integer measurementId, String name, String comparator, double threshold, String optionStatus, AlertDefinition alertDefinitionId, Integer tiggerId, Collection alertConditions) {
        this.type = type;
        this.required = required;
        this.measurementId = measurementId;
        this.name = name;
        this.comparator = comparator;
        this.threshold = threshold;
        this.optionStatus = optionStatus;
        this.alertDefinitionId = alertDefinitionId;
        this.tiggerId = tiggerId;
        this.alertConditions = alertConditions;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public boolean isRequired() {
        return this.required;
    }
    
    public void setRequired(boolean required) {
        this.required = required;
    }
    public Integer getMeasurementId() {
        return this.measurementId;
    }
    
    public void setMeasurementId(Integer measurementId) {
        this.measurementId = measurementId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComparator() {
        return this.comparator;
    }
    
    public void setComparator(String comparator) {
        this.comparator = comparator;
    }
    public double getThreshold() {
        return this.threshold;
    }
    
    public void setThreshold(double threshold) {
        this.threshold = threshold;
    }
    public String getOptionStatus() {
        return this.optionStatus;
    }
    
    public void setOptionStatus(String optionStatus) {
        this.optionStatus = optionStatus;
    }
    public AlertDefinition getAlertDefinitionId() {
        return this.alertDefinitionId;
    }
    
    public void setAlertDefinitionId(AlertDefinition alertDefinitionId) {
        this.alertDefinitionId = alertDefinitionId;
    }
    public Integer getTiggerId() {
        return this.tiggerId;
    }
    
    public void setTiggerId(Integer tiggerId) {
        this.tiggerId = tiggerId;
    }
    public Collection getAlertConditions() {
        return this.alertConditions;
    }
    
    public void setAlertConditions(Collection alertConditions) {
        this.alertConditions = alertConditions;
    }




}


