/*                                                                 
 * NOTE: This copyright does *not* cover user programs that use HQ 
 * program services by normal system calls through the application 
 * program interfaces provided as part of the Hyperic Plug-in Development 
 * Kit or the Hyperic Client Development Kit - this is merely considered 
 * normal use of the program, and does *not* fall under the heading of 
 * "derived work". 
 *  
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc. 
 * This file is part of HQ.         
 *  
 * HQ is free software; you can redistribute it and/or modify 
 * it under the terms version 2 of the GNU General Public License as 
 * published by the Free Software Foundation. This program is distributed 
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. 
 *                
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 
 * USA. 
 */

package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private long _version_;
     private long ctime;
     private AlertDefinition alertDefinitionId;
     private Collection alertActions;
     private Collection alertConditions;
     private Collection userAlerts;

     // Constructors

    /** default constructor */
    public Alert() {
    }

	/** minimal constructor */
    public Alert(long ctime) {
        this.ctime = ctime;
    }
    /** full constructor */
    public Alert(long ctime, AlertDefinition alertDefinitionId, Collection alertActions, Collection alertConditions, Collection userAlerts) {
        this.ctime = ctime;
        this.alertDefinitionId = alertDefinitionId;
        this.alertActions = alertActions;
        this.alertConditions = alertConditions;
        this.userAlerts = userAlerts;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public long getCtime() {
        return this.ctime;
    }
    
    public void setCtime(long ctime) {
        this.ctime = ctime;
    }
    public AlertDefinition getAlertDefinitionId() {
        return this.alertDefinitionId;
    }
    
    public void setAlertDefinitionId(AlertDefinition alertDefinitionId) {
        this.alertDefinitionId = alertDefinitionId;
    }
    public Collection getAlertActions() {
        return this.alertActions;
    }
    
    public void setAlertActions(Collection alertActions) {
        this.alertActions = alertActions;
    }
    public Collection getAlertConditions() {
        return this.alertConditions;
    }
    
    public void setAlertConditions(Collection alertConditions) {
        this.alertConditions = alertConditions;
    }
    public Collection getUserAlerts() {
        return this.userAlerts;
    }
    
    public void setUserAlerts(Collection userAlerts) {
        this.userAlerts = userAlerts;
    }




}


