package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private long _version_;
     private long ctime;
     private AlertDefinition alertDefinitionId;
     private Collection alertActions;
     private Collection alertConditions;
     private Collection userAlerts;

     // Constructors

    /** default constructor */
    public Alert() {
    }

	/** minimal constructor */
    public Alert(long ctime) {
        this.ctime = ctime;
    }
    /** full constructor */
    public Alert(long ctime, AlertDefinition alertDefinitionId, Collection alertActions, Collection alertConditions, Collection userAlerts) {
        this.ctime = ctime;
        this.alertDefinitionId = alertDefinitionId;
        this.alertActions = alertActions;
        this.alertConditions = alertConditions;
        this.userAlerts = userAlerts;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public long getCtime() {
        return this.ctime;
    }
    
    public void setCtime(long ctime) {
        this.ctime = ctime;
    }
    public AlertDefinition getAlertDefinitionId() {
        return this.alertDefinitionId;
    }
    
    public void setAlertDefinitionId(AlertDefinition alertDefinitionId) {
        this.alertDefinitionId = alertDefinitionId;
    }
    public Collection getAlertActions() {
        return this.alertActions;
    }
    
    public void setAlertActions(Collection alertActions) {
        this.alertActions = alertActions;
    }
    public Collection getAlertConditions() {
        return this.alertConditions;
    }
    
    public void setAlertConditions(Collection alertConditions) {
        this.alertConditions = alertConditions;
    }
    public Collection getUserAlerts() {
        return this.userAlerts;
    }
    
    public void setUserAlerts(Collection userAlerts) {
        this.userAlerts = userAlerts;
    }




}


