package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4



/**
 * AlertConditionLog generated by hbm2java
 */
public class AlertConditionLog  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private String value;
     private Alert alertId;
     private AlertCondition conditionId;

     // Constructors

    /** default constructor */
    public AlertConditionLog() {
    }

    /** full constructor */
    public AlertConditionLog(String value, Alert alertId, AlertCondition conditionId) {
        this.value = value;
        this.alertId = alertId;
        this.conditionId = conditionId;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Alert getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Alert alertId) {
        this.alertId = alertId;
    }
    public AlertCondition getConditionId() {
        return this.conditionId;
    }
    
    public void setConditionId(AlertCondition conditionId) {
        this.conditionId = conditionId;
    }




}


