package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4



/**
 * AlertActionLog generated by hbm2java
 */
public class AlertActionLog  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private String detail;
     private Alert alertId;
     private Action actionId;

     // Constructors

    /** default constructor */
    public AlertActionLog() {
    }

	/** minimal constructor */
    public AlertActionLog(String detail, Action actionId) {
        this.detail = detail;
        this.actionId = actionId;
    }
    /** full constructor */
    public AlertActionLog(String detail, Alert alertId, Action actionId) {
        this.detail = detail;
        this.alertId = alertId;
        this.actionId = actionId;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public Alert getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Alert alertId) {
        this.alertId = alertId;
    }
    public Action getActionId() {
        return this.actionId;
    }
    
    public void setActionId(Action actionId) {
        this.actionId = actionId;
    }




}


