/*                                                                 
 * NOTE: This copyright does *not* cover user programs that use HQ 
 * program services by normal system calls through the application 
 * program interfaces provided as part of the Hyperic Plug-in Development 
 * Kit or the Hyperic Client Development Kit - this is merely considered 
 * normal use of the program, and does *not* fall under the heading of 
 * "derived work". 
 *  
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc. 
 * This file is part of HQ.         
 *  
 * HQ is free software; you can redistribute it and/or modify 
 * it under the terms version 2 of the GNU General Public License as 
 * published by the Free Software Foundation. This program is distributed 
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. 
 *                
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 
 * USA. 
 */

package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4



/**
 * AlertActionLog generated by hbm2java
 */
public class AlertActionLog  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private String detail;
     private Alert alertId;
     private Action actionId;

     // Constructors

    /** default constructor */
    public AlertActionLog() {
    }

	/** minimal constructor */
    public AlertActionLog(String detail, Action actionId) {
        this.detail = detail;
        this.actionId = actionId;
    }
    /** full constructor */
    public AlertActionLog(String detail, Alert alertId, Action actionId) {
        this.detail = detail;
        this.alertId = alertId;
        this.actionId = actionId;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public Alert getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Alert alertId) {
        this.alertId = alertId;
    }
    public Action getActionId() {
        return this.actionId;
    }
    
    public void setActionId(Action actionId) {
        this.actionId = actionId;
    }




}


