/*                                                                 
 * NOTE: This copyright does *not* cover user programs that use HQ 
 * program services by normal system calls through the application 
 * program interfaces provided as part of the Hyperic Plug-in Development 
 * Kit or the Hyperic Client Development Kit - this is merely considered 
 * normal use of the program, and does *not* fall under the heading of 
 * "derived work". 
 *  
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc. 
 * This file is part of HQ.         
 *  
 * HQ is free software; you can redistribute it and/or modify 
 * it under the terms version 2 of the GNU General Public License as 
 * published by the Free Software Foundation. This program is distributed 
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. 
 *                
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 
 * USA. 
 */

package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {

    // Fields    

     private long id;
     private long _version_;
     private byte[] eventObject;
     private long ctime;
     private Collection triggerEvents;

     // Constructors

    /** default constructor */
    public Event() {
    }

	/** minimal constructor */
    public Event(byte[] eventObject, long ctime) {
        this.eventObject = eventObject;
        this.ctime = ctime;
    }
    /** full constructor */
    public Event(byte[] eventObject, long ctime, Collection triggerEvents) {
        this.eventObject = eventObject;
        this.ctime = ctime;
        this.triggerEvents = triggerEvents;
    }
    
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    private void setId(long id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public byte[] getEventObject() {
        return this.eventObject;
    }
    
    public void setEventObject(byte[] eventObject) {
        this.eventObject = eventObject;
    }
    public long getCtime() {
        return this.ctime;
    }
    
    public void setCtime(long ctime) {
        this.ctime = ctime;
    }
    public Collection getTriggerEvents() {
        return this.triggerEvents;
    }
    
    public void setTriggerEvents(Collection triggerEvents) {
        this.triggerEvents = triggerEvents;
    }




}


