/*                                                                 
 * NOTE: This copyright does *not* cover user programs that use HQ 
 * program services by normal system calls through the application 
 * program interfaces provided as part of the Hyperic Plug-in Development 
 * Kit or the Hyperic Client Development Kit - this is merely considered 
 * normal use of the program, and does *not* fall under the heading of 
 * "derived work". 
 *  
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc. 
 * This file is part of HQ.         
 *  
 * HQ is free software; you can redistribute it and/or modify 
 * it under the terms version 2 of the GNU General Public License as 
 * published by the Free Software Foundation. This program is distributed 
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. 
 *                
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 
 * USA. 
 */

package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4



/**
 * EventLog generated by hbm2java
 */
public class EventLog  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private String detail;
     private String type;
     private Integer entityType;
     private Integer entityId;
     private long timestamp;
     private String subject;
     private String status;

     // Constructors

    /** default constructor */
    public EventLog() {
    }

	/** minimal constructor */
    public EventLog(String detail, String type, long timestamp) {
        this.detail = detail;
        this.type = type;
        this.timestamp = timestamp;
    }
    /** full constructor */
    public EventLog(String detail, String type, Integer entityType, Integer entityId, long timestamp, String subject, String status) {
        this.detail = detail;
        this.type = type;
        this.entityType = entityType;
        this.entityId = entityId;
        this.timestamp = timestamp;
        this.subject = subject;
        this.status = status;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }
    public Integer getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }
    public long getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


