package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4



/**
 * EventLog generated by hbm2java
 */
public class EventLog  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private String detail;
     private String type;
     private Integer entityType;
     private Integer entityId;
     private long timestamp;
     private String subject;
     private String status;

     // Constructors

    /** default constructor */
    public EventLog() {
    }

	/** minimal constructor */
    public EventLog(String detail, String type, long timestamp) {
        this.detail = detail;
        this.type = type;
        this.timestamp = timestamp;
    }
    /** full constructor */
    public EventLog(String detail, String type, Integer entityType, Integer entityId, long timestamp, String subject, String status) {
        this.detail = detail;
        this.type = type;
        this.entityType = entityType;
        this.entityId = entityId;
        this.timestamp = timestamp;
        this.subject = subject;
        this.status = status;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }
    public Integer getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }
    public long getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


