package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {

    // Fields    

     private long id;
     private long _version_;
     private byte[] eventObject;
     private long ctime;
     private Collection triggerEvents;

     // Constructors

    /** default constructor */
    public Event() {
    }

	/** minimal constructor */
    public Event(byte[] eventObject, long ctime) {
        this.eventObject = eventObject;
        this.ctime = ctime;
    }
    /** full constructor */
    public Event(byte[] eventObject, long ctime, Collection triggerEvents) {
        this.eventObject = eventObject;
        this.ctime = ctime;
        this.triggerEvents = triggerEvents;
    }
    
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    private void setId(long id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public byte[] getEventObject() {
        return this.eventObject;
    }
    
    public void setEventObject(byte[] eventObject) {
        this.eventObject = eventObject;
    }
    public long getCtime() {
        return this.ctime;
    }
    
    public void setCtime(long ctime) {
        this.ctime = ctime;
    }
    public Collection getTriggerEvents() {
        return this.triggerEvents;
    }
    
    public void setTriggerEvents(Collection triggerEvents) {
        this.triggerEvents = triggerEvents;
    }




}


