package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4



/**
 * FiredTrigger generated by hbm2java
 */
public class FiredTrigger  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private Integer triggerId;
     private long timestamp;

     // Constructors

    /** default constructor */
    public FiredTrigger() {
    }

    /** full constructor */
    public FiredTrigger(Integer triggerId, long timestamp) {
        this.triggerId = triggerId;
        this.timestamp = timestamp;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public Integer getTriggerId() {
        return this.triggerId;
    }
    
    public void setTriggerId(Integer triggerId) {
        this.triggerId = triggerId;
    }
    public long getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }




}


