package org.hyperic.hq.events;
// Generated Oct 17, 2006 12:40:43 PM by Hibernate Tools 3.1.0.beta4



/**
 * TriggerEventId generated by hbm2java
 */
public class TriggerEventId  implements java.io.Serializable {

    // Fields    

     private Integer triggerId;
     private Event eventId;

     // Constructors

    /** default constructor */
    public TriggerEventId() {
    }

    /** full constructor */
    public TriggerEventId(Integer triggerId, Event eventId) {
        this.triggerId = triggerId;
        this.eventId = eventId;
    }
    
   
    // Property accessors
    public Integer getTriggerId() {
        return this.triggerId;
    }
    
    public void setTriggerId(Integer triggerId) {
        this.triggerId = triggerId;
    }
    public Event getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Event eventId) {
        this.eventId = eventId;
    }




}


