// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hyperic.hq.domain;

import org.hyperic.hq.domain.ResourceDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ResourceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ResourceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ResourceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ResourceIntegrationTest: @Transactional;
    
    @Autowired
    private ResourceDataOnDemand ResourceIntegrationTest.dod;
    
    @Test
    public void ResourceIntegrationTest.testCountResources() {
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to initialize correctly", dod.getRandomResource());
        long count = org.hyperic.hq.domain.Resource.countResources();
        org.junit.Assert.assertTrue("Counter for 'Resource' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ResourceIntegrationTest.testFindResource() {
        org.hyperic.hq.domain.Resource obj = dod.getRandomResource();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to provide an identifier", id);
        obj = org.hyperic.hq.domain.Resource.findResource(id);
        org.junit.Assert.assertNotNull("Find method for 'Resource' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Resource' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ResourceIntegrationTest.testFindAllResources() {
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to initialize correctly", dod.getRandomResource());
        long count = org.hyperic.hq.domain.Resource.countResources();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Resource', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.hyperic.hq.domain.Resource> result = org.hyperic.hq.domain.Resource.findAllResources();
        org.junit.Assert.assertNotNull("Find all method for 'Resource' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Resource' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ResourceIntegrationTest.testFindResourceEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to initialize correctly", dod.getRandomResource());
        long count = org.hyperic.hq.domain.Resource.countResources();
        if (count > 20) count = 20;
        java.util.List<org.hyperic.hq.domain.Resource> result = org.hyperic.hq.domain.Resource.findResourceEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Resource' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Resource' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ResourceIntegrationTest.testFlush() {
        org.hyperic.hq.domain.Resource obj = dod.getRandomResource();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to provide an identifier", id);
        obj = org.hyperic.hq.domain.Resource.findResource(id);
        org.junit.Assert.assertNotNull("Find method for 'Resource' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyResource(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Resource' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ResourceIntegrationTest.testMerge() {
        org.hyperic.hq.domain.Resource obj = dod.getRandomResource();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to provide an identifier", id);
        obj = org.hyperic.hq.domain.Resource.findResource(id);
        boolean modified =  dod.modifyResource(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.hyperic.hq.domain.Resource merged = (org.hyperic.hq.domain.Resource) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Resource' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ResourceIntegrationTest.testRemove() {
        org.hyperic.hq.domain.Resource obj = dod.getRandomResource();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Resource' failed to provide an identifier", id);
        obj = org.hyperic.hq.domain.Resource.findResource(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Resource' with identifier '" + id + "'", org.hyperic.hq.domain.Resource.findResource(id));
    }
    
}
