/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.common.shared;

/**
 * Local home interface for ServerConfigManager.
 */
public interface ServerConfigManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServerConfigManagerLocal";
   public static final String JNDI_NAME="LocalServerConfigManager";

   public org.hyperic.hq.common.shared.ServerConfigManagerLocal create()
      throws javax.ejb.CreateException;

}
