package org.hyperic.hq.measurement;
// Generated Oct 19, 2006 11:49:50 AM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private long _version_;
     private String name;
     private Integer cid;
     private Collection measurementTemplates;

     // Constructors

    /** default constructor */
    public Category() {
    }

	/** minimal constructor */
    public Category(String name) {
        this.name = name;
    }
    /** full constructor */
    public Category(String name, Integer cid, Collection measurementTemplates) {
        this.name = name;
        this.cid = cid;
        this.measurementTemplates = measurementTemplates;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Collection getMeasurementTemplates() {
        return this.measurementTemplates;
    }
    
    public void setMeasurementTemplates(Collection measurementTemplates) {
        this.measurementTemplates = measurementTemplates;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Category) ) return false;
		 Category castOther = ( Category ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         
         
         
         
         return result;
   }   


}


