package org.hyperic.hq.measurement;
// Generated Oct 19, 2006 11:49:50 AM by Hibernate Tools 3.1.0.beta4


import java.math.BigDecimal;

/**
 * MeasurementData generated by hbm2java
 */
public class MeasurementData  implements java.io.Serializable {

    // Fields    

     private MeasurementDataId id;
     private BigDecimal value;

     // Constructors

    /** default constructor */
    public MeasurementData() {
    }

	/** minimal constructor */
    public MeasurementData(MeasurementDataId id) {
        this.id = id;
    }
    /** full constructor */
    public MeasurementData(MeasurementDataId id, BigDecimal value) {
        this.id = id;
        this.value = value;
    }
    
   
    // Property accessors
    public MeasurementDataId getId() {
        return this.id;
    }
    
    public void setId(MeasurementDataId id) {
        this.id = id;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MeasurementData) ) return false;
		 MeasurementData castOther = ( MeasurementData ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         
         return result;
   }   


}


