package org.hyperic.hq.measurement;
// Generated Oct 19, 2006 11:49:50 AM by Hibernate Tools 3.1.0.beta4



/**
 * MetricProblem generated by hbm2java
 */
public class MetricProblem  implements java.io.Serializable {

    // Fields    

     private MeasurementDataId id;
     private Integer type;
     private Integer additional;

     // Constructors

    /** default constructor */
    public MetricProblem() {
    }

	/** minimal constructor */
    public MetricProblem(MeasurementDataId id, Integer type) {
        this.id = id;
        this.type = type;
    }
    /** full constructor */
    public MetricProblem(MeasurementDataId id, Integer type, Integer additional) {
        this.id = id;
        this.type = type;
        this.additional = additional;
    }
    
   
    // Property accessors
    public MeasurementDataId getId() {
        return this.id;
    }
    
    public void setId(MeasurementDataId id) {
        this.id = id;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(Integer additional) {
        this.additional = additional;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MetricProblem) ) return false;
		 MetricProblem castOther = ( MetricProblem ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         
         
         return result;
   }   


}


