/*                                                                 
 * NOTE: This copyright does *not* cover user programs that use HQ 
 * program services by normal system calls through the application 
 * program interfaces provided as part of the Hyperic Plug-in Development 
 * Kit or the Hyperic Client Development Kit - this is merely considered 
 * normal use of the program, and does *not* fall under the heading of 
 * "derived work". 
 *  
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc. 
 * This file is part of HQ.         
 *  
 * HQ is free software; you can redistribute it and/or modify 
 * it under the terms version 2 of the GNU General Public License as 
 * published by the Free Software Foundation. This program is distributed 
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. 
 *                
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 
 * USA. 
 */

package org.hyperic.hq.measurement;
// Generated Oct 19, 2006 11:49:50 AM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * MonitorableType generated by hbm2java
 */
public class MonitorableType  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private long _version_;
     private String name;
     private Integer cid;
     private Integer appdefType;
     private String plugIn;
     private Collection measurementTemplates;

     // Constructors

    /** default constructor */
    public MonitorableType() {
    }

	/** minimal constructor */
    public MonitorableType(String name, Integer appdefType, String plugIn) {
        this.name = name;
        this.appdefType = appdefType;
        this.plugIn = plugIn;
    }
    /** full constructor */
    public MonitorableType(String name, Integer cid, Integer appdefType, String plugIn, Collection measurementTemplates) {
        this.name = name;
        this.cid = cid;
        this.appdefType = appdefType;
        this.plugIn = plugIn;
        this.measurementTemplates = measurementTemplates;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Integer getAppdefType() {
        return this.appdefType;
    }
    
    public void setAppdefType(Integer appdefType) {
        this.appdefType = appdefType;
    }
    public String getPlugIn() {
        return this.plugIn;
    }
    
    public void setPlugIn(String plugIn) {
        this.plugIn = plugIn;
    }
    public Collection getMeasurementTemplates() {
        return this.measurementTemplates;
    }
    
    public void setMeasurementTemplates(Collection measurementTemplates) {
        this.measurementTemplates = measurementTemplates;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MonitorableType) ) return false;
		 MonitorableType castOther = ( MonitorableType ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         
         
         
         
         
         
         return result;
   }   


}


