package org.hyperic.hq.measurement;
// Generated Oct 19, 2006 11:49:50 AM by Hibernate Tools 3.1.0.beta4



/**
 * RawMeasurement generated by hbm2java
 */
public class RawMeasurement extends org.hyperic.hq.measurement.Measurement implements java.io.Serializable {

    // Fields    

     private String dsn;

     // Constructors

    /** default constructor */
    public RawMeasurement() {
    }

	/** minimal constructor */
    public RawMeasurement(Integer instanceId, long mtime) {
        super(instanceId, mtime);        
    }
    /** full constructor */
    public RawMeasurement(Integer instanceId, MeasurementTemplate template, Integer cid, long mtime, Integer appdefType, String dsn) {
        super(instanceId, template, cid, mtime, appdefType);        
        this.dsn = dsn;
    }
    
   
    // Property accessors
    public String getDsn() {
        return this.dsn;
    }
    
    public void setDsn(String dsn) {
        this.dsn = dsn;
    }




}


