/*                                                                 
 * NOTE: This copyright does *not* cover user programs that use HQ 
 * program services by normal system calls through the application 
 * program interfaces provided as part of the Hyperic Plug-in Development 
 * Kit or the Hyperic Client Development Kit - this is merely considered 
 * normal use of the program, and does *not* fall under the heading of 
 * "derived work". 
 *  
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc. 
 * This file is part of HQ.         
 *  
 * HQ is free software; you can redistribute it and/or modify 
 * it under the terms version 2 of the GNU General Public License as 
 * published by the Free Software Foundation. This program is distributed 
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. 
 *                
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 
 * USA. 
 */

package org.hyperic.hq.measurement;
// Generated Oct 19, 2006 11:49:50 AM by Hibernate Tools 3.1.0.beta4



/**
 * SrnId generated by hbm2java
 */
public class SrnId  implements java.io.Serializable {

    // Fields    

     private Integer appdefType;
     private Integer instanceId;

     // Constructors

    /** default constructor */
    public SrnId() {
    }

    /** full constructor */
    public SrnId(Integer appdefType, Integer instanceId) {
        this.appdefType = appdefType;
        this.instanceId = instanceId;
    }
    
   
    // Property accessors
    public Integer getAppdefType() {
        return this.appdefType;
    }
    
    public void setAppdefType(Integer appdefType) {
        this.appdefType = appdefType;
    }
    public Integer getInstanceId() {
        return this.instanceId;
    }
    
    public void setInstanceId(Integer instanceId) {
        this.instanceId = instanceId;
    }



  // The following is extra code specified in the hbm.xml files

        public boolean equals(Object other)
        {
            if (this == other) return true;
            if (other == null) return false;
            if (!(other instanceof SrnId)) return false;
            SrnId castOther = (SrnId)other;
            return this.getAppdefType().intValue() == castOther.getAppdefType().intValue() &&
                   this.getInstanceId().intValue() == castOther.getInstanceId().intValue();
        }

        public int hashCode()
        {
            return 17;
        }
      
  // end of extra code specified in the hbm.xml files

}


