/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.events.shared;

/**
 * Local interface for HierarchicalAlertingManager.
 */
public interface HierarchicalAlertingManagerLocal
   extends HierarchicalAlertingManagerInterface, javax.ejb.EJBLocalObject
{
   /**
    * Determine whether the measurement events can be suppressed as part of hierarchical alerting
    */
   public void suppressMeasurementEvents( java.util.Map events,boolean isFromAgent ) ;

   /**
    * Perform a simple "secondary" availability check for down platforms.
    */
   public void performSecondaryAvailabilityCheck( java.util.Map downPlatforms ) ;

}
