package org.hyperic.hq.scheduler;
// Generated Nov 3, 2006 4:40:15 PM by Hibernate Tools 3.1.0.beta4



/**
 * QzPausedTriggerGrp generated by hbm2java
 */
public class QzPausedTriggerGrp  implements java.io.Serializable {

    // Fields    

     private String triggerGroup;

     // Constructors

    /** default constructor */
    public QzPausedTriggerGrp() {
    }

    /** full constructor */
    public QzPausedTriggerGrp(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }
    
   
    // Property accessors
    public String getTriggerGroup() {
        return this.triggerGroup;
    }
    
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QzPausedTriggerGrp) ) return false;
		 QzPausedTriggerGrp castOther = ( QzPausedTriggerGrp ) other; 
         
		 return ( (this.getTriggerGroup()==castOther.getTriggerGroup()) || ( this.getTriggerGroup()!=null && castOther.getTriggerGroup()!=null && this.getTriggerGroup().equals(castOther.getTriggerGroup()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTriggerGroup() == null ? 0 : this.getTriggerGroup().hashCode() );
         return result;
   }   


}


