package org.hyperic.hq.scheduler;
// Generated Nov 3, 2006 4:40:15 PM by Hibernate Tools 3.1.0.beta4



/**
 * QzTriggerListener generated by hbm2java
 */
public class QzTriggerListener  implements java.io.Serializable {

    // Fields    

     private QzTriggerListenerId id;
     private QzTrigger trigger;

     // Constructors

    /** default constructor */
    public QzTriggerListener() {
    }

	/** minimal constructor */
    public QzTriggerListener(QzTriggerListenerId id) {
        this.id = id;
    }
    /** full constructor */
    public QzTriggerListener(QzTriggerListenerId id, QzTrigger trigger) {
        this.id = id;
        this.trigger = trigger;
    }
    
   
    // Property accessors
    public QzTriggerListenerId getId() {
        return this.id;
    }
    
    public void setId(QzTriggerListenerId id) {
        this.id = id;
    }
    public QzTrigger getTrigger() {
        return this.trigger;
    }
    
    public void setTrigger(QzTrigger trigger) {
        this.trigger = trigger;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QzTriggerListener) ) return false;
		 QzTriggerListener castOther = ( QzTriggerListener ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         
         return result;
   }   


}


