package org.hyperic.hq.scheduler;
// Generated Nov 3, 2006 4:40:15 PM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * QzTrigger generated by hbm2java
 */
public class QzTrigger  implements java.io.Serializable {

    // Fields    

     private QzTriggerId id;
     private String jobName;
     private String jobGroup;
     private boolean isVolatile;
     private String description;
     private long nextFireTime;
     private long prevFireTime;
     private String triggerState;
     private String triggerType;
     private long startTime;
     private long endTime;
     private String calendarName;
     private Integer misFireInstr;
     private byte[] jobData;
     private QzJobDetail jobDetail;
     private Collection triggerListeners;

     // Constructors

    /** default constructor */
    public QzTrigger() {
    }

	/** minimal constructor */
    public QzTrigger(QzTriggerId id, String jobName, String jobGroup, boolean isVolatile, String triggerState, String triggerType, long startTime) {
        this.id = id;
        this.jobName = jobName;
        this.jobGroup = jobGroup;
        this.isVolatile = isVolatile;
        this.triggerState = triggerState;
        this.triggerType = triggerType;
        this.startTime = startTime;
    }
    /** full constructor */
    public QzTrigger(QzTriggerId id, String jobName, String jobGroup, boolean isVolatile, String description, long nextFireTime, long prevFireTime, String triggerState, String triggerType, long startTime, long endTime, String calendarName, Integer misFireInstr, byte[] jobData, QzJobDetail jobDetail, Collection triggerListeners) {
        this.id = id;
        this.jobName = jobName;
        this.jobGroup = jobGroup;
        this.isVolatile = isVolatile;
        this.description = description;
        this.nextFireTime = nextFireTime;
        this.prevFireTime = prevFireTime;
        this.triggerState = triggerState;
        this.triggerType = triggerType;
        this.startTime = startTime;
        this.endTime = endTime;
        this.calendarName = calendarName;
        this.misFireInstr = misFireInstr;
        this.jobData = jobData;
        this.jobDetail = jobDetail;
        this.triggerListeners = triggerListeners;
    }
    
   
    // Property accessors
    public QzTriggerId getId() {
        return this.id;
    }
    
    public void setId(QzTriggerId id) {
        this.id = id;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public String getJobGroup() {
        return this.jobGroup;
    }
    
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }
    public boolean isIsVolatile() {
        return this.isVolatile;
    }
    
    public void setIsVolatile(boolean isVolatile) {
        this.isVolatile = isVolatile;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getNextFireTime() {
        return this.nextFireTime;
    }
    
    public void setNextFireTime(long nextFireTime) {
        this.nextFireTime = nextFireTime;
    }
    public long getPrevFireTime() {
        return this.prevFireTime;
    }
    
    public void setPrevFireTime(long prevFireTime) {
        this.prevFireTime = prevFireTime;
    }
    public String getTriggerState() {
        return this.triggerState;
    }
    
    public void setTriggerState(String triggerState) {
        this.triggerState = triggerState;
    }
    public String getTriggerType() {
        return this.triggerType;
    }
    
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType;
    }
    public long getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }
    public long getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }
    public String getCalendarName() {
        return this.calendarName;
    }
    
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName;
    }
    public Integer getMisFireInstr() {
        return this.misFireInstr;
    }
    
    public void setMisFireInstr(Integer misFireInstr) {
        this.misFireInstr = misFireInstr;
    }
    public byte[] getJobData() {
        return this.jobData;
    }
    
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }
    public QzJobDetail getJobDetail() {
        return this.jobDetail;
    }
    
    public void setJobDetail(QzJobDetail jobDetail) {
        this.jobDetail = jobDetail;
    }
    public Collection getTriggerListeners() {
        return this.triggerListeners;
    }
    
    public void setTriggerListeners(Collection triggerListeners) {
        this.triggerListeners = triggerListeners;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QzTrigger) ) return false;
		 QzTrigger castOther = ( QzTrigger ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   


}


