package org.hyperic.hq.scheduler;
// Generated Nov 3, 2006 4:40:15 PM by Hibernate Tools 3.1.0.beta4



/**
 * QzTriggerListenerId generated by hbm2java
 */
public class QzTriggerListenerId  implements java.io.Serializable {

    // Fields    

     private String triggerName;
     private String triggerGroup;
     private String triggerListener;

     // Constructors

    /** default constructor */
    public QzTriggerListenerId() {
    }

    /** full constructor */
    public QzTriggerListenerId(String triggerName, String triggerGroup, String triggerListener) {
        this.triggerName = triggerName;
        this.triggerGroup = triggerGroup;
        this.triggerListener = triggerListener;
    }
    
   
    // Property accessors
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }
    public String getTriggerGroup() {
        return this.triggerGroup;
    }
    
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }
    public String getTriggerListener() {
        return this.triggerListener;
    }
    
    public void setTriggerListener(String triggerListener) {
        this.triggerListener = triggerListener;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QzTriggerListenerId) ) return false;
		 QzTriggerListenerId castOther = ( QzTriggerListenerId ) other; 
         
		 return ( (this.getTriggerName()==castOther.getTriggerName()) || ( this.getTriggerName()!=null && castOther.getTriggerName()!=null && this.getTriggerName().equals(castOther.getTriggerName()) ) )
 && ( (this.getTriggerGroup()==castOther.getTriggerGroup()) || ( this.getTriggerGroup()!=null && castOther.getTriggerGroup()!=null && this.getTriggerGroup().equals(castOther.getTriggerGroup()) ) )
 && ( (this.getTriggerListener()==castOther.getTriggerListener()) || ( this.getTriggerListener()!=null && castOther.getTriggerListener()!=null && this.getTriggerListener().equals(castOther.getTriggerListener()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTriggerName() == null ? 0 : this.getTriggerName().hashCode() );
         result = 37 * result + ( getTriggerGroup() == null ? 0 : this.getTriggerGroup().hashCode() );
         result = 37 * result + ( getTriggerListener() == null ? 0 : this.getTriggerListener().hashCode() );
         return result;
   }   


}


