package org.hyperic.hq.authz;
// Generated Oct 17, 2006 12:45:08 PM by Hibernate Tools 3.1.0.beta4



/**
 * ResGrpResMapId generated by hbm2java
 */
public class ResGrpResMapId  implements java.io.Serializable {

    // Fields    

     private Resource resourceId;
     private ResourceGroup resourceGroupId;

     // Constructors

    /** default constructor */
    public ResGrpResMapId() {
    }

    /** full constructor */
    public ResGrpResMapId(Resource resourceId, ResourceGroup resourceGroupId) {
        this.resourceId = resourceId;
        this.resourceGroupId = resourceGroupId;
    }
    
   
    // Property accessors
    public Resource getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(Resource resourceId) {
        this.resourceId = resourceId;
    }
    public ResourceGroup getResourceGroupId() {
        return this.resourceGroupId;
    }
    
    public void setResourceGroupId(ResourceGroup resourceGroupId) {
        this.resourceGroupId = resourceGroupId;
    }




}


