package org.hyperic.hq.authz;
// Generated Oct 17, 2006 12:45:08 PM by Hibernate Tools 3.1.0.beta4


import java.util.Collection;

/**
 * Resource generated by hbm2java
 */
public class Resource  implements java.io.Serializable {

    // Fields    

     private Integer id;
     private long _version_;
     private ResourceType resourceTypeId;
     private Integer instanceId;
     private Integer cid;
     private Integer subjectId;
     private String name;
     private String sortName;
     private boolean fsystem;
     private Collection resourceGroups;
     private Collection group;
     private Collection roles;

     // Constructors

    /** default constructor */
    public Resource() {
    }

    /** full constructor */
    public Resource(ResourceType resourceTypeId, Integer instanceId, Integer cid, Integer subjectId, String name, String sortName, boolean fsystem, Collection resourceGroups, Collection group, Collection roles) {
        this.resourceTypeId = resourceTypeId;
        this.instanceId = instanceId;
        this.cid = cid;
        this.subjectId = subjectId;
        this.name = name;
        this.sortName = sortName;
        this.fsystem = fsystem;
        this.resourceGroups = resourceGroups;
        this.group = group;
        this.roles = roles;
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public ResourceType getResourceTypeId() {
        return this.resourceTypeId;
    }
    
    public void setResourceTypeId(ResourceType resourceTypeId) {
        this.resourceTypeId = resourceTypeId;
    }
    public Integer getInstanceId() {
        return this.instanceId;
    }
    
    public void setInstanceId(Integer instanceId) {
        this.instanceId = instanceId;
    }
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSortName() {
        return this.sortName;
    }
    
    public void setSortName(String sortName) {
        this.sortName = sortName;
    }
    public boolean isFsystem() {
        return this.fsystem;
    }
    
    public void setFsystem(boolean fsystem) {
        this.fsystem = fsystem;
    }
    public Collection getResourceGroups() {
        return this.resourceGroups;
    }
    
    public void setResourceGroups(Collection resourceGroups) {
        this.resourceGroups = resourceGroups;
    }
    public Collection getGroup() {
        return this.group;
    }
    
    public void setGroup(Collection group) {
        this.group = group;
    }
    public Collection getRoles() {
        return this.roles;
    }
    
    public void setRoles(Collection roles) {
        this.roles = roles;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Resource) ) return false;
		 Resource castOther = ( Resource ) other; 
         
		 return ( (this.getResourceTypeId()==castOther.getResourceTypeId()) || ( this.getResourceTypeId()!=null && castOther.getResourceTypeId()!=null && this.getResourceTypeId().equals(castOther.getResourceTypeId()) ) )
 && ( (this.getInstanceId()==castOther.getInstanceId()) || ( this.getInstanceId()!=null && castOther.getInstanceId()!=null && this.getInstanceId().equals(castOther.getInstanceId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         return result;
   }   


}


