/*
 * NOTE: This copyright does *not* cover user programs that use HQ
 * program services by normal system calls through the application
 * program interfaces provided as part of the Hyperic Plug-in Development
 * Kit or the Hyperic Client Development Kit - this is merely considered
 * normal use of the program, and does *not* fall under the heading of
 * "derived work".
 * 
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc.
 * This file is part of HQ.
 * 
 * HQ is free software; you can redistribute it and/or modify
 * it under the terms version 2 of the GNU General Public License as
 * published by the Free Software Foundation. This program is distributed
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package org.hyperic.hq.authz;

import java.util.Collection;
import java.util.Iterator;

import org.hyperic.hq.authz.shared.RoleValue;

/**
 * Role generated by hbm2java
 */
public class Role extends AuthzNamedEntity implements java.io.Serializable {

    // Fields    

     private String name;
     private Integer cid;
     private String sortName;
     private String description;
     private boolean system;
     private Resource resource;
     private Collection resourceGroups;
     private Collection operations;
     private Collection subjects;

     private RoleValue roleValue = new RoleValue();
     
     // Constructors

    /** default constructor */
    public Role() {
    }

	/** minimal constructor */
    public Role(RoleValue val) {
        this.name = val.getName();
    }
    /** full constructor */
    public Role(String name, Integer cid, String sortName, String description,
                boolean fsystem, Resource resourceId, Collection resourceGroups,
                Collection operations, Collection subjects) {
        this.name = name;
        this.cid = cid;
        this.sortName = sortName;
        this.description = description;
        this.system = fsystem;
        this.resource = resourceId;
        this.resourceGroups = resourceGroups;
        this.operations = operations;
        this.subjects = subjects;
    }
    
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getSortName() {
        return this.sortName;
    }
    
    public void setSortName(String sortName) {
        this.sortName = sortName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isSystem() {
        return this.system;
    }
    
    public void setSystem(boolean fsystem) {
        this.system = fsystem;
    }
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resourceId) {
        this.resource = resourceId;
    }
    public Collection getResourceGroups() {
        return this.resourceGroups;
    }
    
    public void setResourceGroups(Collection resourceGroups) {
        this.resourceGroups = resourceGroups;
    }
    public Collection getOperations() {
        return this.operations;
    }
    
    public void setOperations(Collection operations) {
        this.operations = operations;
    }
    public Collection getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Collection subjects) {
        this.subjects = subjects;
    }


    public RoleValue getRoleValue() {
        roleValue.setDescription(getDescription());
        roleValue.setId(getId());
        roleValue.setName(getName());
        roleValue.setSortName(getSortName());
        roleValue.setSystem(isSystem());
        
        roleValue.removeAllOperationValues();
        if (getOperations() != null) {
            for (Iterator it = getOperations().iterator(); it.hasNext(); ) {
                Operation op = (Operation) it.next();
                roleValue.addOperationValue(op.getOperationValue());
            }
        }

        return roleValue;
    }

    public void setRoleValue(RoleValue roleValue) {
        this.roleValue = roleValue;
    }

    public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Role) ) return false;
		 Role castOther = ( Role ) other; 
         
		 return ((this.getName() == castOther.getName()) ||
                 (this.getName() != null
                && castOther.getName() != null && this.getName()
                .equals(castOther.getName())));
    }
   
    public int hashCode() {
        int result = super.hashCode();
        result = 37 * result +
                ((getSortName() != null) ? getSortName().hashCode() : 0);

        result = 37 * result + (isSystem() ? 0 : 1);

        result = 37 * result +
                ((getDescription() != null) ? getDescription().hashCode() : 0);

        result = 37 * result +
                ((getOperations() != null) ? getOperations().hashCode() : 0);
        return result;
   }   


}


