package org.hyperic.hq.authz;
// Generated Oct 17, 2006 12:45:08 PM by Hibernate Tools 3.1.0.beta4



/**
 * RoleResourceGroupMapId generated by hbm2java
 */
public class RoleResourceGroupMapId  implements java.io.Serializable {

    // Fields    

     private Role roleId;
     private ResourceGroup resourceGroupId;

     // Constructors

    /** default constructor */
    public RoleResourceGroupMapId() {
    }

    /** full constructor */
    public RoleResourceGroupMapId(Role roleId, ResourceGroup resourceGroupId) {
        this.roleId = roleId;
        this.resourceGroupId = resourceGroupId;
    }
    
   
    // Property accessors
    public Role getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Role roleId) {
        this.roleId = roleId;
    }
    public ResourceGroup getResourceGroupId() {
        return this.resourceGroupId;
    }
    
    public void setResourceGroupId(ResourceGroup resourceGroupId) {
        this.resourceGroupId = resourceGroupId;
    }
}


