package org.hyperic.hq.authz;
// Generated Oct 17, 2006 12:45:08 PM by Hibernate Tools 3.1.0.beta4



/**
 * RoleOperMap generated by hbm2java
 */
public class RoleOperMap  implements java.io.Serializable {

    // Fields    

     private RoleOperationMapId id;
     private Integer cid;

     // Constructors

    /** default constructor */
    public RoleOperMap() {
    }

	/** minimal constructor */
    public RoleOperMap(RoleOperationMapId id) {
        this.id = id;
    }
    /** full constructor */
    public RoleOperMap(RoleOperationMapId id, Integer cid) {
        this.id = id;
        this.cid = cid;
    }
    
   
    // Property accessors
    public RoleOperationMapId getId() {
        return this.id;
    }
    
    public void setId(RoleOperationMapId id) {
        this.id = id;
    }
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }




}


