package org.hyperic.hq.authz;
// Generated Oct 17, 2006 12:45:08 PM by Hibernate Tools 3.1.0.beta4



/**
 * UserConfigResp generated by hbm2java
 */
public class UserConfigResp  implements java.io.Serializable {

    // Fields    
     private Integer id;
     private long _version_;
     private byte[] prefResponse;
     /** default constructor */
    public UserConfigResp() {
    }

    /** full constructor */
    public UserConfigResp(byte[] prefResponse, AuthzSubject subject) {
        this.prefResponse = prefResponse;
        setId(subject.getId());
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    public void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public byte[] getPrefResponse() {
        return this.prefResponse;
    }
    
    public void setPrefResponse(byte[] prefResponse) {
        this.prefResponse = prefResponse;
    }
}

