// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hyperic.hq.inventory.domain;

import java.util.List;
import java.util.Random;
import org.hyperic.hq.inventory.domain.Agent;
import org.springframework.stereotype.Component;

privileged aspect AgentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AgentDataOnDemand: @Component;
    
    private Random AgentDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Agent> AgentDataOnDemand.data;
    
    public Agent AgentDataOnDemand.getNewTransientAgent(int index) {
        org.hyperic.hq.inventory.domain.Agent obj = new org.hyperic.hq.inventory.domain.Agent();
        obj.setAddress("address_" + index);
        obj.setAgentToken("agentToken_" + index);
        obj.setAgentVersion("agentVersion_" + index);
        obj.setAuthToken("authToken_" + index);
        obj.setPort(new Integer(index));
        obj.setUnidirectional(Boolean.TRUE);
        return obj;
    }
    
    public Agent AgentDataOnDemand.getSpecificAgent(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Agent obj = data.get(index);
        return Agent.findAgent(obj.getId());
    }
    
    public Agent AgentDataOnDemand.getRandomAgent() {
        init();
        Agent obj = data.get(rnd.nextInt(data.size()));
        return Agent.findAgent(obj.getId());
    }
    
    public boolean AgentDataOnDemand.modifyAgent(Agent obj) {
        return false;
    }
    
    public void AgentDataOnDemand.init() {
        data = org.hyperic.hq.inventory.domain.Agent.findAgentEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Agent' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.hyperic.hq.inventory.domain.Agent>();
        for (int i = 0; i < 10; i++) {
            org.hyperic.hq.inventory.domain.Agent obj = getNewTransientAgent(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
