// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hyperic.hq.inventory.domain;

import java.util.List;
import java.util.Random;
import org.hyperic.hq.inventory.domain.Config;
import org.springframework.stereotype.Component;

privileged aspect ConfigDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConfigDataOnDemand: @Component;
    
    private Random ConfigDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Config> ConfigDataOnDemand.data;
    
    public Config ConfigDataOnDemand.getNewTransientConfig(int index) {
        org.hyperic.hq.inventory.domain.Config obj = new org.hyperic.hq.inventory.domain.Config();
        obj.set_autoInventoryResponse(null);
        obj.set_controlResponse(null);
        obj.set_measurementResponse(null);
        obj.set_productResponse(null);
        return obj;
    }
    
    public Config ConfigDataOnDemand.getSpecificConfig(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Config obj = data.get(index);
        return Config.findConfig(obj.getId());
    }
    
    public Config ConfigDataOnDemand.getRandomConfig() {
        init();
        Config obj = data.get(rnd.nextInt(data.size()));
        return Config.findConfig(obj.getId());
    }
    
    public boolean ConfigDataOnDemand.modifyConfig(Config obj) {
        return false;
    }
    
    public void ConfigDataOnDemand.init() {
        data = org.hyperic.hq.inventory.domain.Config.findConfigEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Config' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.hyperic.hq.inventory.domain.Config>();
        for (int i = 0; i < 10; i++) {
            org.hyperic.hq.inventory.domain.Config obj = getNewTransientConfig(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
