// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hyperic.hq.inventory.domain;

import java.util.List;
import java.util.Random;
import org.hyperic.hq.inventory.domain.Ip;
import org.springframework.stereotype.Component;

privileged aspect IpDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IpDataOnDemand: @Component;
    
    private Random IpDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Ip> IpDataOnDemand.data;
    
    public Ip IpDataOnDemand.getNewTransientIp(int index) {
        org.hyperic.hq.inventory.domain.Ip obj = new org.hyperic.hq.inventory.domain.Ip();
        obj.setAddress("address_" + index);
        obj.setMacAddress("macAddress_" + index);
        obj.setNetmask("netmask_" + index);
        obj.setPlatform(null);
        return obj;
    }
    
    public Ip IpDataOnDemand.getSpecificIp(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Ip obj = data.get(index);
        return Ip.findIp(obj.getId());
    }
    
    public Ip IpDataOnDemand.getRandomIp() {
        init();
        Ip obj = data.get(rnd.nextInt(data.size()));
        return Ip.findIp(obj.getId());
    }
    
    public boolean IpDataOnDemand.modifyIp(Ip obj) {
        return false;
    }
    
    public void IpDataOnDemand.init() {
        data = org.hyperic.hq.inventory.domain.Ip.findIpEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Ip' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.hyperic.hq.inventory.domain.Ip>();
        for (int i = 0; i < 10; i++) {
            org.hyperic.hq.inventory.domain.Ip obj = getNewTransientIp(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
