// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hyperic.hq.inventory.domain;

import org.hyperic.hq.inventory.domain.PlatformDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PlatformIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlatformIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PlatformIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PlatformIntegrationTest: @Transactional;
    
    @Autowired
    private PlatformDataOnDemand PlatformIntegrationTest.dod;
    
    @Test
    public void PlatformIntegrationTest.testCountPlatforms() {
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", dod.getRandomPlatform());
        long count = org.hyperic.hq.inventory.domain.Platform.countPlatforms();
        org.junit.Assert.assertTrue("Counter for 'Platform' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PlatformIntegrationTest.testFindPlatform() {
        org.hyperic.hq.inventory.domain.Platform obj = dod.getRandomPlatform();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to provide an identifier", id);
        obj = org.hyperic.hq.inventory.domain.Platform.findPlatform(id);
        org.junit.Assert.assertNotNull("Find method for 'Platform' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Platform' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PlatformIntegrationTest.testFindAllPlatforms() {
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", dod.getRandomPlatform());
        long count = org.hyperic.hq.inventory.domain.Platform.countPlatforms();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Platform', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.hyperic.hq.inventory.domain.Platform> result = org.hyperic.hq.inventory.domain.Platform.findAllPlatforms();
        org.junit.Assert.assertNotNull("Find all method for 'Platform' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Platform' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PlatformIntegrationTest.testFindPlatformEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", dod.getRandomPlatform());
        long count = org.hyperic.hq.inventory.domain.Platform.countPlatforms();
        if (count > 20) count = 20;
        java.util.List<org.hyperic.hq.inventory.domain.Platform> result = org.hyperic.hq.inventory.domain.Platform.findPlatformEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Platform' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Platform' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PlatformIntegrationTest.testFlush() {
        org.hyperic.hq.inventory.domain.Platform obj = dod.getRandomPlatform();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to provide an identifier", id);
        obj = org.hyperic.hq.inventory.domain.Platform.findPlatform(id);
        org.junit.Assert.assertNotNull("Find method for 'Platform' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPlatform(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Platform' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlatformIntegrationTest.testMerge() {
        org.hyperic.hq.inventory.domain.Platform obj = dod.getRandomPlatform();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to provide an identifier", id);
        obj = org.hyperic.hq.inventory.domain.Platform.findPlatform(id);
        boolean modified =  dod.modifyPlatform(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.hyperic.hq.inventory.domain.Platform merged = (org.hyperic.hq.inventory.domain.Platform) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Platform' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlatformIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", dod.getRandomPlatform());
        org.hyperic.hq.inventory.domain.Platform obj = dod.getNewTransientPlatform(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Platform' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Platform' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PlatformIntegrationTest.testRemove() {
        org.hyperic.hq.inventory.domain.Platform obj = dod.getRandomPlatform();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Platform' failed to provide an identifier", id);
        obj = org.hyperic.hq.inventory.domain.Platform.findPlatform(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Platform' with identifier '" + id + "'", org.hyperic.hq.inventory.domain.Platform.findPlatform(id));
    }
    
}
