// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hyperic.hq.inventory.domain;

import java.util.List;
import java.util.Random;
import org.hyperic.hq.inventory.domain.PlatformType;
import org.springframework.stereotype.Component;

privileged aspect PlatformTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlatformTypeDataOnDemand: @Component;
    
    private Random PlatformTypeDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PlatformType> PlatformTypeDataOnDemand.data;
    
    public PlatformType PlatformTypeDataOnDemand.getNewTransientPlatformType(int index) {
        org.hyperic.hq.inventory.domain.PlatformType obj = new org.hyperic.hq.inventory.domain.PlatformType();
        obj.setPlugin("plugin_" + index);
        return obj;
    }
    
    public PlatformType PlatformTypeDataOnDemand.getSpecificPlatformType(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PlatformType obj = data.get(index);
        return PlatformType.findPlatformType(obj.getId());
    }
    
    public PlatformType PlatformTypeDataOnDemand.getRandomPlatformType() {
        init();
        PlatformType obj = data.get(rnd.nextInt(data.size()));
        return PlatformType.findPlatformType(obj.getId());
    }
    
    public boolean PlatformTypeDataOnDemand.modifyPlatformType(PlatformType obj) {
        return false;
    }
    
    public void PlatformTypeDataOnDemand.init() {
        data = org.hyperic.hq.inventory.domain.PlatformType.findPlatformTypeEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PlatformType' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.hyperic.hq.inventory.domain.PlatformType>();
        for (int i = 0; i < 10; i++) {
            org.hyperic.hq.inventory.domain.PlatformType obj = getNewTransientPlatformType(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
