/*
 * NOTE: This copyright does *not* cover user programs that use HQ
 * program services by normal system calls through the application
 * program interfaces provided as part of the Hyperic Plug-in Development
 * Kit or the Hyperic Client Development Kit - this is merely considered
 * normal use of the program, and does *not* fall under the heading of
 * "derived work".
 *
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc.
 * This file is part of HQ.
 *
 * HQ is free software; you can redistribute it and/or modify
 * it under the terms version 2 of the GNU General Public License as
 * published by the Free Software Foundation. This program is distributed
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package org.hyperic.hq.authz.server.session;

// Generated Oct 17, 2006 12:45:08 PM by Hibernate Tools 3.1.0.beta4



/**
 * AuthzSubjRoleMapId generated by hbm2java
 */
public class AuthzSubjRoleMapId  implements java.io.Serializable {

    // Fields    

     private Role role;
     private AuthzSubject subject;

     // Constructors

    /** default constructor */
    public AuthzSubjRoleMapId() {
    }

    /** full constructor */
    public AuthzSubjRoleMapId(Role roleId, AuthzSubject subjectId) {
        this.role = roleId;
        this.subject = subjectId;
    }
    
   
    // Property accessors
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public AuthzSubject getSubject() {
        return this.subject;
    }
    
    public void setSubject(AuthzSubject subject) {
        this.subject = subject;
    }




}


