/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.authz.shared;

/**
 * Local home interface for AuthzSubjectManager.
 */
public interface AuthzSubjectManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AuthzSubjectManagerLocal";
   public static final String JNDI_NAME="LocalAuthzSubjectManager";

   public org.hyperic.hq.authz.shared.AuthzSubjectManagerLocal create()
      throws javax.ejb.CreateException;

}
