/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.authz.shared;

/**
 * Local home interface for RoleManager.
 */
public interface RoleManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RoleManagerLocal";
   public static final String JNDI_NAME="LocalRoleManager";

   public org.hyperic.hq.authz.shared.RoleManagerLocal create()
      throws javax.ejb.CreateException;

}
