package org.hyperic.hq.authz.server.session;




/**
 * ResGrpResMapId generated by hbm2java
 */
public class ResGrpResMapId  implements java.io.Serializable {

    // Fields    

     private Resource resourceId;
     private ResourceGroup resourceGroupId;

     // Constructors

    /** default constructor */
    public ResGrpResMapId() {
    }

    /** full constructor */
    public ResGrpResMapId(Resource resourceId, ResourceGroup resourceGroupId) {
        this.resourceId = resourceId;
        this.resourceGroupId = resourceGroupId;
    }
    
   
    // Property accessors
    public Resource getResource() {
        return this.resourceId;
    }
    
    public void setResource(Resource resourceId) {
        this.resourceId = resourceId;
    }
    public ResourceGroup getResourceGroup() {
        return this.resourceGroupId;
    }
    
    public void setResourceGroup(ResourceGroup resourceGroupId) {
        this.resourceGroupId = resourceGroupId;
    }




}


