package org.hyperic.hq.authz.server.session;




/**
 * RoleOperationMapId generated by hbm2java
 */
public class RoleOperationMapId  implements java.io.Serializable {

    // Fields    

     private Role roleId;
     private Operation operationId;

     // Constructors

    /** default constructor */
    public RoleOperationMapId() {
    }

    /** full constructor */
    public RoleOperationMapId(Role roleId, Operation operationId) {
        this.roleId = roleId;
        this.operationId = operationId;
    }
    
   
    // Property accessors
    public Role getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Role roleId) {
        this.roleId = roleId;
    }
    public Operation getOperationId() {
        return this.operationId;
    }
    
    public void setOperationId(Operation operationId) {
        this.operationId = operationId;
    }




}


