/*
 * NOTE: This copyright does *not* cover user programs that use HQ
 * program services by normal system calls through the application
 * program interfaces provided as part of the Hyperic Plug-in Development
 * Kit or the Hyperic Client Development Kit - this is merely considered
 * normal use of the program, and does *not* fall under the heading of
 * "derived work".
 *
 * Copyright (C) [2004, 2005, 2006], Hyperic, Inc.
 * This file is part of HQ.
 *
 * HQ is free software; you can redistribute it and/or modify
 * it under the terms version 2 of the GNU General Public License as
 * published by the Free Software Foundation. This program is distributed
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 */

package org.hyperic.hq.authz.server.session;




/**
 * UserConfigResp generated by hbm2java
 */
public class UserConfigResp  implements java.io.Serializable {

    // Fields    
     private Integer id;
     private long _version_;
     private byte[] prefResponse;
     /** default constructor */
    public UserConfigResp() {
    }

    /** full constructor */
    public UserConfigResp(byte[] prefResponse, AuthzSubject subject) {
        this.prefResponse = prefResponse;
        setId(subject.getId());
    }
    
   
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    private void setId(Integer id) {
        this.id = id;
    }
    public long get_version_() {
        return this._version_;
    }
    
    protected void set_version_(long _version_) {
        this._version_ = _version_;
    }
    public byte[] getPrefResponse() {
        return this.prefResponse;
    }
    
    protected void setPrefResponse(byte[] prefResponse) {
        this.prefResponse = prefResponse;
    }
}

