/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.scheduler.shared;

/**
 * Local home interface for Scheduler.
 */
public interface SchedulerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SchedulerLocal";
   public static final String JNDI_NAME="LocalQuartzScheduler";

   public org.hyperic.hq.scheduler.shared.SchedulerLocal create()
      throws javax.ejb.CreateException;

}
