package org.hyperic.hq.events.server.session;

import org.hyperic.hq.bizapp.shared.action.EmailActionConfig;
import org.hyperic.util.StringUtil;
import org.hyperic.util.config.EncodingException;

import java.util.Set;
// Generated Nov 15, 2006 3:20:57 PM by Hibernate Tools 3.2.0.beta8


/**
 * EscalationAction generated by hbm2java
 */
public class EscalationAction implements java.io.Serializable {

    // Fields    

    private Action action;
    private long waitTime;

    /**
     *
     * @param type  Action Type
     * @param notifs  list of notification types
     * @param waitTime  time to wait until escalating to the next level
     * @return
     */
    public static EscalationAction createEmailAction(int type, Set notifs,
                                                     long waitTime) {
        EscalationAction eact = new EscalationAction();
        Action act = Action.createEmailAction(type, notifs);
        eact.setAction(act);
        eact.setWaitTime(waitTime);
        return eact;
    }

    // Constructors

    /**
     * default constructor
     */
    protected EscalationAction() {
    }

    /**
     * full constructor
     */
    protected EscalationAction(Action action, long waitTime) {
        this.action = action;
        this.waitTime = waitTime;
    }


    // Property accessors
    public Action getAction() {
        return this.action;
    }

    public void setAction(Action action) {
        this.action = action;
    }

    public long getWaitTime() {
        return this.waitTime;
    }

    public void setWaitTime(long waitTime) {
        this.waitTime = waitTime;
    }
}


