/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.auth.shared;

/**
 * Local home interface for AuthManager.
 */
public interface AuthManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AuthManagerLocal";
   public static final String JNDI_NAME="LocalAuthManager";

   public org.hyperic.hq.auth.shared.AuthManagerLocal create()
      throws javax.ejb.CreateException;

}
