/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.appdef.shared;

/**
 * Local home interface for AgentManager.
 */
public interface AgentManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AgentManagerLocal";
   public static final String JNDI_NAME="LocalAgentManager";

   public org.hyperic.hq.appdef.shared.AgentManagerLocal create()
      throws javax.ejb.CreateException;

}
