/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.appdef.shared;

/**
 * Local home interface for AppdefStatManager.
 */
public interface AppdefStatManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AppdefStatManagerLocal";
   public static final String JNDI_NAME="LocalAppdefStatManager";

   public org.hyperic.hq.appdef.shared.AppdefStatManagerLocal create()
      throws javax.ejb.CreateException;

}
