/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.appdef.shared;

/**
 * Local home interface for CPropManager.
 */
public interface CPropManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CPropManagerLocal";
   public static final String JNDI_NAME="LocalCPropManager";

   public org.hyperic.hq.appdef.shared.CPropManagerLocal create()
      throws javax.ejb.CreateException;

}
