/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.appdef.shared;

/**
 * Local home interface for ResourceAuxLogManager.
 */
public interface ResourceAuxLogManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ResourceAuxLogManagerLocal";
   public static final String JNDI_NAME="LocalResourceAuxLogManager";

   public org.hyperic.hq.appdef.shared.ResourceAuxLogManagerLocal create()
      throws javax.ejb.CreateException;

}
