/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.appdef.shared;

/**
 * Local interface for ResourceAuxLogManager.
 */
public interface ResourceAuxLogManagerLocal
   extends javax.ejb.EJBLocalObject
{

   public org.hyperic.hq.appdef.server.session.ResourceAuxLogPojo create( org.hyperic.hq.galerts.server.session.GalertAuxLog log,org.hyperic.hq.appdef.galerts.ResourceAuxLog logInfo ) ;

   public void remove( org.hyperic.hq.galerts.server.session.GalertAuxLog log ) ;

   public org.hyperic.hq.appdef.server.session.ResourceAuxLogPojo find( org.hyperic.hq.galerts.server.session.GalertAuxLog log ) ;

   public void removeAll( org.hyperic.hq.galerts.server.session.GalertDef def ) ;

}
