/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.appdef.shared;

/**
 * Local home interface for VirtualManager.
 */
public interface VirtualManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/VirtualManagerLocal";
   public static final String JNDI_NAME="LocalVirtualManager";

   public org.hyperic.hq.appdef.shared.VirtualManagerLocal create()
      throws javax.ejb.CreateException;

}
