/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.measurement.shared;

/**
 * Local home interface for AvailabilityManager.
 */
public interface AvailabilityManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AvailabilityManagerLocal";
   public static final String JNDI_NAME="LocalAvailabilityManager";

   public org.hyperic.hq.measurement.shared.AvailabilityManagerLocal create()
      throws javax.ejb.CreateException;

}
