/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.measurement.shared;

/**
 * Local interface for DataCompress.
 */
public interface DataCompressLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Entry point for data compression routines
    */
   public void compressData(  ) throws javax.naming.NamingException, java.sql.SQLException;

}
