/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.measurement.shared;

/**
 * Local home interface for MeasurementProcessor.
 */
public interface MeasurementProcessorLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MeasurementProcessorLocal";
   public static final String JNDI_NAME="LocalMeasurementProcessor";

   public org.hyperic.hq.measurement.shared.MeasurementProcessorLocal create()
      throws javax.ejb.CreateException;

}
