/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.measurement.shared;

/**
 * Local home interface for SRNManager.
 */
public interface SRNManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SRNManagerLocal";
   public static final String JNDI_NAME="SRNManager";

   public org.hyperic.hq.measurement.shared.SRNManagerLocal create()
      throws javax.ejb.CreateException;

}
