/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.measurement.shared;

/**
 * Local interface for TrackerManager.
 */
public interface TrackerManagerLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Enable log and config tracking for a resource if it has been enabled.
    */
   public void enableTrackers( org.hyperic.hq.authz.server.session.AuthzSubject subject,org.hyperic.hq.appdef.shared.AppdefEntityID id,org.hyperic.util.config.ConfigResponse config ) throws org.hyperic.hq.authz.shared.PermissionException, org.hyperic.hq.product.PluginException;

   /**
    * Disable log and config tracking for a resource.
    */
   public void disableTrackers( org.hyperic.hq.authz.server.session.AuthzSubject subject,org.hyperic.hq.appdef.shared.AppdefEntityID id,org.hyperic.util.config.ConfigResponse config ) throws org.hyperic.hq.authz.shared.PermissionException, org.hyperic.hq.product.PluginException;

   /**
    * Toggle log and config tracking for the resource.
    */
   public void toggleTrackers( org.hyperic.hq.authz.server.session.AuthzSubject subject,org.hyperic.hq.appdef.shared.AppdefEntityID id,org.hyperic.util.config.ConfigResponse config ) throws org.hyperic.hq.authz.shared.PermissionException, org.hyperic.hq.product.PluginException;

}
