/**
 * NOTE: This copyright does *not* cover user programs that use HQ
 * program services by normal system calls through the application
 * program interfaces provided as part of the Hyperic Plug-in Development
 * Kit or the Hyperic Client Development Kit - this is merely considered
 * normal use of the program, and does *not* fall under the heading of
 *  "derived work".
 *
 *  Copyright (C) [2009-2011], VMware, Inc.
 *  This file is part of HQ.
 *
 *  HQ is free software; you can redistribute it and/or modify
 *  it under the terms version 2 of the GNU General Public License as
 *  published by the Free Software Foundation. This program is distributed
 *  in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 *  even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more
 *  details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 *  USA.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.07 at 01:58:59 PM CST 
//


package org.hyperic.hq.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlertDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlertDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourcePrototype" type="{}ResourcePrototype"/>
 *         &lt;element name="Escalation" type="{}Escalation"/>
 *         &lt;element name="AlertCondition" type="{}AlertCondition" maxOccurs="unbounded"/>
 *         &lt;element name="AlertAction" type="{}AlertAction" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="controlFiltered" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="notifyFiltered" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="willRecover" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="range" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="frequency" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="active" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ctime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="mtime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertDefinition", propOrder = {
    "resourcePrototype",
    "escalation",
    "alertCondition",
    "alertAction"
})
public class AlertDefinition {

    @XmlElement(name = "ResourcePrototype", required = true)
    protected ResourcePrototype resourcePrototype;
    @XmlElement(name = "Escalation", required = true)
    protected Escalation escalation;
    @XmlElement(name = "AlertCondition", required = true)
    protected List<AlertCondition> alertCondition;
    @XmlElement(name = "AlertAction", required = true)
    protected List<AlertAction> alertAction;
    @XmlAttribute(name = "controlFiltered", required = true)
    protected boolean controlFiltered;
    @XmlAttribute(name = "notifyFiltered", required = true)
    protected boolean notifyFiltered;
    @XmlAttribute(name = "willRecover", required = true)
    protected boolean willRecover;
    @XmlAttribute(name = "range", required = true)
    protected int range;
    @XmlAttribute(name = "count", required = true)
    protected int count;
    @XmlAttribute(name = "frequency", required = true)
    protected int frequency;
    @XmlAttribute(name = "active", required = true)
    protected boolean active;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;
    @XmlAttribute(name = "priority", required = true)
    protected int priority;
    @XmlAttribute(name = "parent")
    protected Integer parent;
    @XmlAttribute(name = "description", required = true)
    protected String description;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "ctime")
    protected Long ctime;
    @XmlAttribute(name = "mtime")
    protected Long mtime;

    /**
     * Gets the value of the resourcePrototype property.
     * 
     * @return
     *     possible object is
     *     {@link ResourcePrototype }
     *     
     */
    public ResourcePrototype getResourcePrototype() {
        return resourcePrototype;
    }

    /**
     * Sets the value of the resourcePrototype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourcePrototype }
     *     
     */
    public void setResourcePrototype(ResourcePrototype value) {
        this.resourcePrototype = value;
    }

    /**
     * Gets the value of the escalation property.
     * 
     * @return
     *     possible object is
     *     {@link Escalation }
     *     
     */
    public Escalation getEscalation() {
        return escalation;
    }

    /**
     * Sets the value of the escalation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Escalation }
     *     
     */
    public void setEscalation(Escalation value) {
        this.escalation = value;
    }

    /**
     * Gets the value of the alertCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alertCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlertCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlertCondition }
     * 
     * 
     */
    public List<AlertCondition> getAlertCondition() {
        if (alertCondition == null) {
            alertCondition = new ArrayList<AlertCondition>();
        }
        return this.alertCondition;
    }

    /**
     * Gets the value of the alertAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alertAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlertAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlertAction }
     * 
     * 
     */
    public List<AlertAction> getAlertAction() {
        if (alertAction == null) {
            alertAction = new ArrayList<AlertAction>();
        }
        return this.alertAction;
    }

    /**
     * Gets the value of the controlFiltered property.
     * 
     */
    public boolean isControlFiltered() {
        return controlFiltered;
    }

    /**
     * Sets the value of the controlFiltered property.
     * 
     */
    public void setControlFiltered(boolean value) {
        this.controlFiltered = value;
    }

    /**
     * Gets the value of the notifyFiltered property.
     * 
     */
    public boolean isNotifyFiltered() {
        return notifyFiltered;
    }

    /**
     * Sets the value of the notifyFiltered property.
     * 
     */
    public void setNotifyFiltered(boolean value) {
        this.notifyFiltered = value;
    }

    /**
     * Gets the value of the willRecover property.
     * 
     */
    public boolean isWillRecover() {
        return willRecover;
    }

    /**
     * Sets the value of the willRecover property.
     * 
     */
    public void setWillRecover(boolean value) {
        this.willRecover = value;
    }

    /**
     * Gets the value of the range property.
     * 
     */
    public int getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     */
    public void setRange(int value) {
        this.range = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     */
    public int getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     */
    public void setFrequency(int value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParent(Integer value) {
        this.parent = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the ctime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * Sets the value of the ctime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCtime(Long value) {
        this.ctime = value;
    }

    /**
     * Gets the value of the mtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMtime() {
        return mtime;
    }

    /**
     * Sets the value of the mtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMtime(Long value) {
        this.mtime = value;
    }

}
