//
/**
 * NOTE: This copyright does *not* cover user programs that use HQ
 * program services by normal system calls through the application
 * program interfaces provided as part of the Hyperic Plug-in Development
 * Kit or the Hyperic Client Development Kit - this is merely considered
 * normal use of the program, and does *not* fall under the heading of
 *  "derived work".
 *
 *  Copyright (C) [2009-2011], VMware, Inc.
 *  This file is part of HQ.
 *
 *  HQ is free software; you can redistribute it and/or modify
 *  it under the terms version 2 of the GNU General Public License as
 *  published by the Free Software Foundation. This program is distributed
 *  in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 *  even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more
 *  details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 *  USA.
 *
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.07 at 01:58:59 PM CST 
//


package org.hyperic.hq.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EscalationAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EscalationAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Notify" type="{}Notify" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="notifyType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sms" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="syslogMeta" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="syslogProduct" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="syslogVersion" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="snmpAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="snmpNotificationMechanism" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="snmpOid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="snmpVariableBindings" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wait" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="actionType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EscalationAction", propOrder = {
    "notify"
})
public class EscalationAction {

    @XmlElement(name = "Notify", required = true)
    protected List<Notify> notify;
    @XmlAttribute(name = "notifyType", required = true)
    protected String notifyType;
    @XmlAttribute(name = "sms", required = true)
    protected boolean sms;
    @XmlAttribute(name = "syslogMeta")
    @XmlSchemaType(name = "anySimpleType")
    protected String syslogMeta;
    @XmlAttribute(name = "syslogProduct")
    @XmlSchemaType(name = "anySimpleType")
    protected String syslogProduct;
    @XmlAttribute(name = "syslogVersion")
    @XmlSchemaType(name = "anySimpleType")
    protected String syslogVersion;
    @XmlAttribute(name = "snmpAddress")
    protected String snmpAddress;
    @XmlAttribute(name = "snmpNotificationMechanism")
    protected String snmpNotificationMechanism;
    @XmlAttribute(name = "snmpOid")
    protected String snmpOid;
    @XmlAttribute(name = "snmpVariableBindings")
    protected String snmpVariableBindings;
    @XmlAttribute(name = "wait", required = true)
    protected long wait;
    @XmlAttribute(name = "actionType", required = true)
    protected String actionType;
    @XmlAttribute(name = "id", required = true)
    protected int id;

    /**
     * Gets the value of the notify property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notify property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotify().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Notify }
     * 
     * 
     */
    public List<Notify> getNotify() {
        if (notify == null) {
            notify = new ArrayList<Notify>();
        }
        return this.notify;
    }

    /**
     * Gets the value of the notifyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyType() {
        return notifyType;
    }

    /**
     * Sets the value of the notifyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyType(String value) {
        this.notifyType = value;
    }

    /**
     * Gets the value of the sms property.
     * 
     */
    public boolean isSms() {
        return sms;
    }

    /**
     * Sets the value of the sms property.
     * 
     */
    public void setSms(boolean value) {
        this.sms = value;
    }

    /**
     * Gets the value of the syslogMeta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogMeta() {
        return syslogMeta;
    }

    /**
     * Sets the value of the syslogMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogMeta(String value) {
        this.syslogMeta = value;
    }

    /**
     * Gets the value of the syslogProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogProduct() {
        return syslogProduct;
    }

    /**
     * Sets the value of the syslogProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogProduct(String value) {
        this.syslogProduct = value;
    }

    /**
     * Gets the value of the syslogVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogVersion() {
        return syslogVersion;
    }

    /**
     * Sets the value of the syslogVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogVersion(String value) {
        this.syslogVersion = value;
    }

    /**
     * Gets the value of the snmpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnmpAddress() {
        return snmpAddress;
    }

    /**
     * Sets the value of the snmpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnmpAddress(String value) {
        this.snmpAddress = value;
    }

    /**
     * Gets the value of the snmpNotificationMechanism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnmpNotificationMechanism() {
        return snmpNotificationMechanism;
    }

    /**
     * Sets the value of the snmpNotificationMechanism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnmpNotificationMechanism(String value) {
        this.snmpNotificationMechanism = value;
    }

    /**
     * Gets the value of the snmpOid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnmpOid() {
        return snmpOid;
    }

    /**
     * Sets the value of the snmpOid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnmpOid(String value) {
        this.snmpOid = value;
    }

    /**
     * Gets the value of the snmpVariableBindings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnmpVariableBindings() {
        return snmpVariableBindings;
    }

    /**
     * Sets the value of the snmpVariableBindings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnmpVariableBindings(String value) {
        this.snmpVariableBindings = value;
    }

    /**
     * Gets the value of the wait property.
     * 
     */
    public long getWait() {
        return wait;
    }

    /**
     * Sets the value of the wait property.
     * 
     */
    public void setWait(long value) {
        this.wait = value;
    }

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionType(String value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
