/*
 * Generated by XDoclet - Do not edit!
 */
package org.hyperic.hq.hqu.shared;

/**
 * Local interface for UIPluginManager.
 */
public interface UIPluginManagerLocal
   extends javax.ejb.EJBLocalObject
{

   public org.hyperic.hq.hqu.server.session.UIPlugin createPlugin( java.lang.String name,java.lang.String ver ) ;

   public org.hyperic.hq.hqu.server.session.UIPlugin createOrUpdate( java.lang.String name,java.lang.String version ) ;

   public org.hyperic.hq.hqu.server.session.View createAdminView( org.hyperic.hq.hqu.server.session.UIPlugin p,org.hyperic.hq.hqu.ViewDescriptor d ) ;

   public org.hyperic.hq.hqu.server.session.View createMastheadView( org.hyperic.hq.hqu.server.session.UIPlugin p,org.hyperic.hq.hqu.ViewDescriptor d ) ;

   public org.hyperic.hq.hqu.server.session.View createResourceView( org.hyperic.hq.hqu.server.session.UIPlugin p,org.hyperic.hq.hqu.ViewDescriptor d ) ;

   public org.hyperic.hq.hqu.server.session.UIPlugin findPluginByName( java.lang.String name ) ;

   public org.hyperic.hq.hqu.server.session.UIPlugin findPluginById( java.lang.Integer id ) ;

   public org.hyperic.hq.hqu.server.session.View findViewById( java.lang.Integer id ) ;

   public org.hyperic.hq.hqu.server.session.Attachment findAttachmentById( java.lang.Integer id ) ;

   /**
    * Remove a plugin, all its views, and attach points from the system.
    */
   public void deletePlugin( org.hyperic.hq.hqu.server.session.UIPlugin p ) ;

   public void detach( org.hyperic.hq.hqu.server.session.Attachment a ) ;

   public void attachView( org.hyperic.hq.hqu.server.session.ViewMasthead view,org.hyperic.hq.hqu.server.session.ViewMastheadCategory cat ) ;

   public void attachView( org.hyperic.hq.hqu.server.session.ViewAdmin view,org.hyperic.hq.hqu.server.session.ViewAdminCategory cat ) ;

   public void attachView( org.hyperic.hq.hqu.server.session.ViewResource view,org.hyperic.hq.hqu.server.session.ViewResourceCategory cat,org.hyperic.hq.authz.server.session.Resource r ) ;

   public void updatePlugin( org.hyperic.hq.hqu.server.session.UIPlugin p,java.lang.String version ) ;

   /**
    * Finds all {@link UIPlugin}s
    */
   public java.util.Collection findAll(  ) ;

   /**
    * Find all the views attached via a specific attach type
    * @return a collection of {@link AttachType}s
    */
   public java.util.Collection findViews( org.hyperic.hq.hqu.server.session.AttachType type ) ;

   /**
    * Find all attachments for a specific type
    * @return a collection of {@link AttachmentDescriptor}s
    */
   public java.util.Collection findAttachments( org.hyperic.hq.hqu.server.session.AttachType type,org.hyperic.hq.authz.server.session.AuthzSubject user ) ;

   public org.hyperic.hq.hqu.AttachmentDescriptor findAttachmentDescriptorById( java.lang.Integer id,org.hyperic.hq.authz.server.session.AuthzSubject user ) ;

   /**
    * Find attachments for a resource.
    * @return a collection of {@link AttachmentDescriptor}s
    */
   public java.util.Collection findAttachments( org.hyperic.hq.appdef.shared.AppdefEntityID ent,org.hyperic.hq.hqu.server.session.ViewResourceCategory cat,org.hyperic.hq.authz.server.session.AuthzSubject user ) ;

}
